# Generated by Django 3.2.12 on 2023-09-30 20:19

import ai_canvas.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_staff', '0009_designerorientation_designshape_designshapecategory_fontcatagorylist_fontdata_fontfamily_fontlanguag'),
        ('ai_workspace', '0014_auto_20230930_1725'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiAssertscategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CanvasCatagories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CanvasDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=50, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canvasdesign_created_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designer_project', to='ai_workspace.project')),
                ('project_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_staff.socialmediasize')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('updated_at',),
            },
        ),
        migrations.CreateModel(
            name='CanvasDownloadFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CanvasSourceUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_id', models.CharField(blank=True, max_length=300, null=True)),
                ('source_text', models.CharField(blank=True, max_length=2000, null=True)),
                ('prev_text', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CanvasTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('template_json', models.JSONField()),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='aidesign_templates/thumbnails/')),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmojiCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageListCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageurl', models.CharField(blank=True, max_length=3000, null=True)),
                ('preview_img', models.CharField(blank=True, max_length=3000, null=True)),
                ('tags', models.CharField(blank=True, max_length=300, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyTemplateDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=50, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_created_by', to=settings.AUTH_USER_MODEL)),
                ('project_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_cat_mytemplate', to='ai_staff.socialmediasize')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_ai_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateGlobalDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(blank=True, max_length=50, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('is_pro', models.BooleanField()),
                ('is_published', models.BooleanField()),
                ('description', models.CharField(blank=True, max_length=600, null=True)),
                ('thumbnail_page', models.FileField(blank=True, null=True, upload_to='templates_page/thumbnails/')),
                ('export_page', models.FileField(blank=True, null=True, upload_to='templates_page/exports/')),
                ('json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_global_categoty', to='ai_staff.socialmediasize')),
                ('template_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_page_lang', to='ai_staff.languages')),
            ],
        ),
        migrations.CreateModel(
            name='TextTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_thumbnail', models.FileField(blank=True, null=True, upload_to='text_template')),
                ('text_template_json', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdpartyImageMedium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='aidesign/thirdpartyimage')),
            ],
        ),
        migrations.CreateModel(
            name='TextboxUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('text', models.CharField(blank=True, max_length=1000, null=True)),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_text_box', to='ai_canvas.canvasdesign')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(blank=True, max_length=500, null=True)),
                ('global_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_global_page', to='ai_canvas.templateglobaldesign')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_keywords', models.CharField(max_length=100)),
                ('text_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='txt_temp', to='ai_canvas.texttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='SourceImageAssetsCanvasTranslate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to=ai_canvas.models.user_directory_path_canvas_source_image_assets)),
                ('canvas_design_img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aidesign_design_image_assets', to='ai_canvas.canvasdesign')),
            ],
        ),
        migrations.CreateModel(
            name='MyTemplateDesignPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_template_thumbnail', models.FileField(blank=True, null=True, upload_to=ai_canvas.models.user_directory_path_canvas_mytemplatedesign_thumbnails)),
                ('my_template_export', models.FileField(blank=True, null=True, upload_to=ai_canvas.models.user_directory_path_canvas_mytemplatedesign_exports)),
                ('my_template_json', models.JSONField(default=dict, null=True)),
                ('my_template_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_template_page', to='ai_canvas.mytemplatedesign')),
            ],
        ),
        migrations.CreateModel(
            name='FontFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=2000, null=True)),
                ('font_family', models.FileField(blank=True, null=True, upload_to=ai_canvas.models.user_directory_path_font_file)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='font_created_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmojiData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji_name', models.CharField(blank=True, max_length=300, null=True)),
                ('data', models.TextField()),
                ('emoji_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emoji_cat_data', to='ai_canvas.emojicategory')),
            ],
        ),
        migrations.CreateModel(
            name='CanvasUserImageAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=ai_canvas.models.user_directory_path_canvas_image_assets)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to=ai_canvas.models.user_directory_path_canvas_user_imageassets)),
                ('status', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='img_asst_created_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img_asst_ai_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CanvasTranslatedJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('undo_hide_tar', models.BooleanField(default=False)),
                ('canvas_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_translate', to='ai_canvas.canvasdesign')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canvas_job', to='ai_workspace.job')),
                ('source_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_locale', to='ai_staff.languageslocale')),
                ('target_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='ai_staff.languageslocale')),
            ],
        ),
        migrations.CreateModel(
            name='CanvasTargetJsonFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to=ai_canvas.models.user_directory_path_canvas_target_json_thumbnails)),
                ('export_file', models.FileField(blank=True, null=True, upload_to=ai_canvas.models.user_directory_path_canvas_target_json_exports)),
                ('json', models.JSONField(null=True)),
                ('page_no', models.IntegerField()),
                ('canvas_trans_json', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_json_tar', to='ai_canvas.canvastranslatedjson')),
            ],
            options={
                'ordering': ('page_no',),
            },
        ),
        migrations.CreateModel(
            name='CanvasSourceJsonFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to=ai_canvas.models.user_directory_path_canvas_source_json_thumbnails)),
                ('export_file', models.FileField(blank=True, null=True, upload_to=ai_canvas.models.user_directory_path_canvas_source_json_exports)),
                ('json', models.JSONField(null=True)),
                ('page_no', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('undo_hide_src', models.BooleanField(default=False)),
                ('canvas_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_json_src', to='ai_canvas.canvasdesign')),
            ],
            options={
                'ordering': ('page_no',),
            },
        ),
        migrations.CreateModel(
            name='AssetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageurl', models.FileField(blank=True, null=True, upload_to='asset-image')),
                ('blob', models.FileField(blank=True, null=True, upload_to='asset-blob')),
                ('preview_img', models.FileField(blank=True, null=True, upload_to='asset_thumbnail')),
                ('tags', models.TextField(blank=True, null=True)),
                ('positive_prompt', models.TextField(blank=True, null=True)),
                ('negative_prompt', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=300, null=True)),
                ('is_store', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_asset_cat', to='ai_staff.imagecategories')),
                ('image_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_asset_image', to='ai_canvas.assetcategory')),
                ('user_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_asset_image', to='ai_canvas.canvasuserimageassets')),
            ],
        ),
        migrations.CreateModel(
            name='AiAsserts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageurl', models.FileField(blank=True, null=True, upload_to='Ai-assert')),
                ('preview_img', models.FileField(blank=True, null=True, upload_to='Ai-assert')),
                ('tags', models.TextField(blank=True, null=True)),
                ('positive_prompt', models.TextField(blank=True, null=True)),
                ('negative_prompt', models.TextField(blank=True, null=True)),
                ('user', models.CharField(blank=True, max_length=2000, null=True)),
                ('status', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_staff.imagecategories')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_canvas.aiassertscategory')),
            ],
        ),
        migrations.AddConstraint(
            model_name='textboxupdate',
            constraint=models.UniqueConstraint(fields=('canvas', 'text_id'), name='ai_canvas_textboxupdate_unique'),
        ),
        migrations.AddConstraint(
            model_name='canvastranslatedjson',
            constraint=models.UniqueConstraint(fields=('canvas_design', 'source_language', 'target_language'), name='ai_canvas_canvastranslatedjson_unique'),
        ),
        migrations.AddConstraint(
            model_name='canvassourcejsonfiles',
            constraint=models.UniqueConstraint(fields=('canvas_design', 'page_no'), name='ai_canvas_canvassourcejsonfiles_unique'),
        ),
    ]
