# Generated by Django 3.2.12 on 2023-11-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_canvas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvasuserimageassets',
            name='duration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='canvasuserimageassets',
            name='frame',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
