

ALLOWED_FILE_EXTENSIONSFILTER_MAPPER ={
     ('.txt',): 'plain-text-processor',
     ('.odt', '.odp', '.ods'): 'openoffice-file-processor',
     ('.html', '.htm', '.xhtml'): 'html-processor',
     ('.tmx',): 'tmx-processor',
     ('.json',): 'json-processor',
     ('.properties',): 'properties-filter',
     ('.po', '.pot'): 'po-processor',
     ('.ts',): 'ts-processor',
     ('.doc',
      '.docx',
      '.xlsx',
      '.pptx',
      '.docm',
      '.dotx',
      '.dotm'): 'open-xml-processor',
     ('.xlf'): 'xlf-processor',
     ('.xliff'): 'xliff-processor',
     ('.md',): 'mark-down-processor',
     ('.rtf',): 'rtf-processor',
     ('.idml',): 'idml-processor',
     ('.sdlxliff',): 'sdl-package-processor',
     ('.resx',): 'resx-processor',
     ('.srt',): 'srt-processor',
     ('.csv', '.tsv'): 'table-processor',
     ('.strings',): 'strings-processor',
     ('.md',): 'mark-down-processor',
     ('.xml',) : "android-resources-processor", #java-properties-xml-processor
     ('.stringsdict',) : "apple-strings-dict-processor",
     ('.dtd',) : "dtd-processor",
     ('.php',) : "php-processor",
     ('.yaml', '.yml') : "yaml-processor",
 }

def flatten_mapper(data):
    ret = {}
    for k, v in data.items():
        for _ in k:
            ret[_] = v

    return ret

ALLOWED_FILE_EXTENSIONSFILTER_MAPPER_FLATTEN = flatten_mapper(ALLOWED_FILE_EXTENSIONSFILTER_MAPPER)

CURRENT_SUPPORT_FILE_EXTENSIONS_LIST = [
    ".txt", ".html", ".xhtml", ".tsv", ".csv", ".odp", ".ods", ".odt", ".json",
    ".properties", ".po", ".pot", ".docx", ".xlsx", ".pptx", ".xliff", ".xlf",
    ".idml", ".srt", ".strings", ".md", ".xml", ".stringsdict", ".dtd",
    ".php", ".yaml", ".yml", ".epub",'.pdf',
]#".dotx" -> file processing pending

EMPTY_SEGMENT_CHARACTERS = [
    "\xa0", "\n", "\ufeff",
]

LINGVANEX_LANGUAGE_MAPPER ={
('af',):'af_ZA',
('sq',):'sq_AL',
('am',):'am_ET',
('ar',):'ar_EG',
('ar',):'ar_SA',
('ar',):'ar_AE',
('hy',):'hy_AM',
('az',):'az_AZ',
('eu',):'eu_ES',
('be',):'be_BY',
('bn',):'bn_BD',
('bs',):'bs_BA',
('bg',):'bg_BG',
('ca',):'ca_ES',
('ceb',):'ceb_PH',
('ny',):'ny_MW',
('zh-Hans',):'zh-Hans_CN',
('zh-Hant',):'zh-Hant_TW',
('co',):'co_FR',
('ht',):'ht_HT',
('hr',):'hr_HR',
('cs',):'cs_CZ',
('da',):'da_DK',
('nl',):'nl_NL',
# ('en',):'en_AU',
('en',):'en_GB',
# ('en',):'en_US',
('eo',):'eo_WORLD',
('et',):'et_EE',
('fi',):'fi_FI',
('fr',):'fr_CA',
('fr',):'fr_FR',
('fy',):'fy_NL',
('gl',):'gl_ES',
('ka',):'ka_GE',
('de',):'de_DE',
('el',):'el_GR',
('gu',):'gu_IN',
('ha',):'ha_NE',
('haw',):'haw_US',
('he',):'he_IL',
('hi',):'hi_IN',
('hmn',):'hmn_CN',
('hu',):'hu_HU',
('is',):'is_IS',
('ig',):'ig_NG',
('id',):'id_ID',
('ga',):'ga_IE',
('it',):'it_IT',
('ja',):'ja_JP',
('jv',):'jv_ID',
('kn',):'kn_IN',
('kk',):'kk_KZ',
('km',):'km_KH',
('rw',):'rw_RW',
('ko',):'ko_KR',
('ku',):'ku_IR',
('ky',):'ky_KG',
('lo',):'lo_LA',
('la',):'la_VAT',
('lv',):'lv_LV',
('lt',):'lt_LT',
('lb',):'lb_LU',
('mk',):'mk_MK',
('mg',):'mg_MG',
('ms',):'ms_MY',
('ml',):'ml_IN',
('mt',):'mt_MT',
('mi',):'mi_NZ',
('mr',):'mr_IN',
('mn',):'mn_MN',
('my',):'my_MM',
('ne',):'ne_NP',
('no',):'no_NO',
('or',):'or_OR',
('ps',):'ps_AF',
('fa',):'fa_IR',
('pl',):'pl_PL',
('pt',):'pt_PT',
('pt',):'pt_BR',
('pa',):'pa_PK',
('ro',):'ro_RO',
('ru',):'ru_RU',
('sm',):'sm_WS',
('gd',):'gd_GB',
('sr-Cyrl',):'sr-Cyrl_RS',
('st',):'st_LS',
('sn',):'sn_ZW',
('sd',):'sd_PK',
('si',):'si_LK',
('sk',):'sk_SK',
('sl',):'sl_SI',
('so',):'so_SO',
('es',):'es_ES',
('es',):'es_MX',
('es',):'es_US',
('su',):'su_ID',
('sw',):'sw_TZ',
('sv',):'sv_SE',
('tl',):'tl_PH',
('tg',):'tg_TJ',
('ta',):'ta_IN',
('tt',):'tt_TT',
('te',):'te_IN',
('th',):'th_TH',
('tr',):'tr_TR',
('tk',):'tk_TK',
('uk',):'uk_UA',
('ur',):'ur_PK',
('ug',):'ug_UG',
('uz',):'uz_UZ',
('vi',):'vi_VN',
('cy',):'cy_GB',
('xh',):'xh_ZA',
('yi',):'yi_IL',
('yo',):'yo_NG',
('zu',):'zu_ZA',

 }
