version: "3.3"

services:
  spring-service2:
    build:  ../ai_spring-okapi/
    command: mvn spring-boot:run # java -jar /home/testprj-1.0-SNAPSHOT.jar  –server.port=8088 --debug
    volumes:
      - .:/code/
      - .:/ai_home/
    networks:
      - conn_merge
    ports:
      - 8090:8090

  ai_tms:
    build: .
    # command: gunicorn -w 4 transedit.wsgi -b 0.0.0.0:8000 --timeout 90
    # command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    command: bash -c "python manage.py runserver 0.0.0.0:8089"
    volumes:
      - .:/ai_home/
    ports:
      - "8089:8089"
      - "8889:8889"
    networks:
      - conn_merge
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    # links:
    #   - postgres
    # depends_on:
    #   - postgres
  
  # pg_bouncer:
  #   image: bitnami/pgbouncer:latest
  #   container_name: pg_bouncer
  #   restart: unless-stopped
  #   ports:
  #     - "6432:6432"
  #   environment:
  #     POSTGRESQL_USERNAME: postgres
  #     POSTGRESQL_PASSWORD: admin@10000
  #     POSTGRESQL_DATABASE: ailaysa
  #     POSTGRESQL_HOST: postgres
  #     POSTGRESQL_PORT: 5432
  #     PGBOUNCER_PORT: 6432
  #     PGBOUNCER_POOL_MODE: transaction
# ​
  # postgres:
  #   image: postgres:latest   #
  #   container_name: postgres
  #   restart: unless-stopped
  #   # command: mysql -uailaysap_guest -pguest-dj  ailaysap_ai2020 < file.sql
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./file.sql:/file.sql
  #   networks:
  #     - conn_merge
  #   environment:
  #     POSTGRES_DB: postgres
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: admin@10000
  
  # pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ailaysa@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: s4F@134
  #   ports:
  #     - "5050:80"
    # networks:
    #   - conn_merge

    # links:
    #   - spring-service
    #   - mysql

#   spring-service:
#     build:  ../spring_ailaysa/
#     command: java -jar /home/testprj-1.0-SNAPSHOT.jar --debug
#     volumes:
#       - .:/code/
#     networks:
#       - conn
#     ports:
#     - 8080:8080

#   redis:
#     image: "redis:alpine"
#     networks:
#       - conn

#   web:
#     build: .
#     # command: gunicorn -w 4 transedit.wsgi -b 0.0.0.0:8000 --timeout 90
#     command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
#     volumes:
#       - .:/code/
#     ports:
#       - "8000:8000"
#     networks:
#       - conn
#     links:
#       - spring-service
#       - mysql
#     environment:
#       - django_secret_key=at5mt513dohdcrxnhgte24zb9g%g_%7)i$$%x1#i(0+&ieg3
#       - Debug=True
#     depends_on:
#       - mysql
#       - spring-service
#       - redis
#       - celery
#   celery:
#     build: .
#     command: bash -c 'export C_FORCE_ROOT='true' && celery -A dj_ailaysa_slim worker -l info'
#     volumes:
#       - .:/code
#     depends_on:
# #      - db
#       - redis
#     networks:
#       - conn

#   mysql:
#     image: mariadb/server:latest   #
#     restart: unless-stopped
#     command: --default-authentication-plugin=mysql_native_password
#     # command: mysql -uailaysap_guest -pguest-dj  ailaysap_ai2020 < file.sql
#     ports:
#       - "3307:3306"
#     volumes:
#       - /my/custom:/etc/mysql/mariadb.conf.d/
#       - ./file.sql:/file.sql
#     networks:
#       - conn
#     environment:
#       MYSQL_DATABASE: ailaysap_ai2020
#       MYSQL_USER: ailaysap_guest
#       MYSQL_PASSWORD: guest-dj
#       MYSQL_ROOT_PASSWORD: secret

# #  admin:
# #    image: adminer
# #    networks:
# #      - conn
# #    ports:
# #      - "8080:8080"

networks:
  conn_merge:
    driver: bridge

# # bash -c "
# #     python manage.py migrate
# #     && python manage.py runserver 0.0.0.0:8000
# #   "
# #143.110.241.161
# #https://www.thepythoncode.com/article/using-google-drive--api-in-python
