# Generated by Django 3.2.4 on 2022-01-06 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubOAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_token', models.CharField(max_length=255)),
                ('ai_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_name', models.TextField()),
                ('is_localize_registered', models.BooleanField(default=False)),
                ('is_alive_in_github', models.BooleanField(default=True)),
                ('github_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_repository_set', to='github_.githuboauthtoken')),
            ],
        ),
        migrations.CreateModel(
            name='FetchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_fetched_on', models.DateTimeField(auto_now=True)),
                ('github_token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_fetch_info', to='github_.githuboauthtoken')),
            ],
        ),
    ]
