# Generated by Django 3.2.4 on 2022-03-03 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import integerations.github_.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_workspace', '0007_alter_file_options'),
        ('controller', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=255)),
                ('is_localize_registered', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('accessed_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GithubApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('accessed_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('oauth_token', models.CharField(max_length=255, validators=[integerations.github_.models.GithubApp.validate_oauth_token])),
                ('ai_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('assign_task', 'Assign task'),),
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_name', models.TextField()),
                ('repository_fullname', models.TextField()),
                ('is_localize_registered', models.BooleanField(default=False)),
                ('is_alive_in_github', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('accessed_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('github_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_repository_set', to='github_.githubapp')),
            ],
            options={
                'permissions': (('owner_repository', 'Owner'),),
            },
        ),
        migrations.CreateModel(
            name='HookDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.TextField()),
                ('hook_name', models.TextField()),
                ('destination_name', models.TextField()),
                ('hook_cli_path', models.URLField()),
                ('password', models.TextField()),
                ('hookdeck_url', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_hookdeck_set', to='ai_workspace.project')),
            ],
        ),
        migrations.CreateModel(
            name='FetchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_fetched_on', models.DateTimeField(auto_now=True)),
                ('github_token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_fetch_info', to='github_.githubapp')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DownloadProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_hash', models.TextField(null=True)),
                ('controller', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controller_github_downloadproject', to='controller.downloadcontroller')),
                ('project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_github_downloadproject', to='ai_workspace.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_localize_registered', models.BooleanField(default=False)),
                ('file', models.CharField(max_length=255)),
                ('file_path', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('accessed_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_contentfiles_set', to='github_.branch')),
                ('controller', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='github_contentfile', to='controller.filecontroller')),
                ('uploaded_file', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='github_contentfile', to='ai_workspace.file')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_branches_set', to='github_.repository'),
        ),
        migrations.AddConstraint(
            model_name='githubapp',
            constraint=models.UniqueConstraint(fields=('ai_user', 'username'), name='Duplicate github usernames not allowed for one ai-user ...'),
        ),
    ]
