# Generated by Django 3.2.4 on 2022-01-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='githuboauthtoken',
            name='username',
            field=models.CharField(default='dummy user', max_length=255),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='githuboauthtoken',
            constraint=models.UniqueConstraint(fields=('ai_user', 'username'), name='Duplicate github usernames not allowed for one ai-user ...'),
        ),
    ]
