# Generated by Django 3.2.4 on 2022-02-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github_', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'permissions': (('owner_repository', 'Owner'),)},
        ),
    ]
