# Generated by Django 3.2.4 on 2022-02-21 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0022_alter_taskdetails_options'),
        ('controller', '0001_initial'),
        ('github_', '0002_alter_repository_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentfile',
            name='controller',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='github_contentfile', to='controller.filecontroller'),
        ),
        migrations.AlterField(
            model_name='contentfile',
            name='uploaded_file',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='github_contentfile', to='ai_workspace.file'),
        ),
    ]
