# Generated by Django 3.2.4 on 2022-01-10 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github_', '0002_auto_20220107_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='githuboauthtoken',
            options={'permissions': (('assign_task', 'Assign task'),)},
        ),
    ]
