# Generated by Django 3.2.4 on 2022-01-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_', '0003_alter_githuboauthtoken_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='repository_fullname',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
