# Generated by Django 3.2.4 on 2022-02-21 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
        ('ai_workspace', '0022_alter_taskdetails_options'),
        ('github_', '0003_auto_20220221_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadproject',
            name='controller',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controller_github_downloadproject', to='controller.downloadcontroller'),
        ),
        migrations.AlterField(
            model_name='downloadproject',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_github_downloadproject', to='ai_workspace.project'),
        ),
    ]
