# Generated by Django 3.2.4 on 2022-01-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_', '0005_auto_20220111_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githuboauthtoken',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='githuboauthtoken',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
