# Generated by Django 3.2.4 on 2022-01-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_', '0007_auto_20220111_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contentfile',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contentfile',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
