# Generated by Django 3.2.4 on 2022-01-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_', '0009_contentfile_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentfile',
            name='file_path',
            field=models.TextField(),
        ),
    ]
