# Generated by Django 3.2.4 on 2022-01-26 11:14

from django.db import migrations, models
import django.shortcuts


class Migration(migrations.Migration):

    dependencies = [
        ('github_', '0010_alter_contentfile_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='HookDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.TextField(default=django.shortcuts.get_object_or_404)),
            ],
        ),
    ]
