# Generated by Django 3.2.4 on 2022-01-28 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0002_alter_file_options'),
        ('github_', '0011_hookdeck'),
    ]

    operations = [
        migrations.AddField(
            model_name='hookdeck',
            name='destination_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hookdeck',
            name='hook_cli_path',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='hookdeck',
            name='hook_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hookdeck',
            name='hookdeck_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hookdeck',
            name='password',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hookdeck',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_hookdeck_set', to='ai_workspace.project'),
        ),
        migrations.AlterField(
            model_name='hookdeck',
            name='source_name',
            field=models.TextField(null=True),
        ),
    ]
