# Generated by Django 3.2.4 on 2022-01-30 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0002_alter_file_options'),
        ('github_', '0013_auto_20220128_0744'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_downloadproject', to='ai_workspace.project')),
            ],
        ),
        migrations.CreateModel(
            name='Concrete2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='project_abs', to='ai_workspace.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Concrete1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='project_abs', to='ai_workspace.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
