# Generated by Django 3.2.4 on 2022-01-31 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0002_alter_file_options'),
        ('controller', '__first__'),
        ('github_', '0014_concrete1_concrete2_downloadproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concrete2',
            name='project',
        ),
        migrations.AddField(
            model_name='contentfile',
            name='file_controller',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controller_contentfile', to='controller.filecontroller'),
        ),
        migrations.AddField(
            model_name='contentfile',
            name='uploaded_file',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_workspace.file'),
        ),
        migrations.AddField(
            model_name='downloadproject',
            name='commit_hash',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='downloadproject',
            name='controller',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controller_downloadproject', to='controller.downloadcontroller'),
        ),
        migrations.AlterField(
            model_name='downloadproject',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_downloadproject', to='ai_workspace.project'),
        ),
        migrations.DeleteModel(
            name='Concrete1',
        ),
        migrations.DeleteModel(
            name='Concrete2',
        ),
    ]
