# Generated by Django 3.2.4 on 2022-01-31 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github_', '0015_auto_20220131_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentfile',
            old_name='file_controller',
            new_name='controller',
        ),
    ]
