# Generated by Django 3.2.4 on 2022-02-15 09:41

from django.db import migrations, models
import integerations.github_.models


class Migration(migrations.Migration):

    dependencies = [
        ('github_', '0016_rename_file_controller_contentfile_controller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githuboauthtoken',
            name='oauth_token',
            field=models.CharField(max_length=255, validators=[integerations.github_.models.GithubApp.validate_oauth_token]),
        ),
    ]
