# Generated by Django 3.2.4 on 2022-02-15 11:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('github_', '0017_alter_githuboauthtoken_oauth_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GithubOAuthToken',
            new_name='GithubApp',
        ),
    ]
