# Generated by Django 3.2.4 on 2022-02-16 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github_', '0018_rename_githuboauthtoken_githubapp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'permissions': (('owner_%(app_label)_%(class)s', 'Owner'),)},
        ),
    ]
