# Generated by Django 3.2.4 on 2021-09-27 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_workspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_word_count', models.IntegerField()),
                ('total_char_count', models.IntegerField()),
                ('total_segment_count', models.IntegerField()),
                ('google_api_cost_est', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_document_set', to='ai_workspace.file')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_job_set', to='ai_workspace.job')),
            ],
        ),
        migrations.CreateModel(
            name='MT_Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='TranslationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=25)),
                ('status_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TextUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okapi_ref_translation_unit_id', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_text_unit_set', to='ai_workspace_okapi.document')),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_workspace.task')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(blank=True)),
                ('target', models.TextField(blank=True, null=True)),
                ('temp_target', models.TextField(blank=True, null=True)),
                ('coded_source', models.TextField(blank=True, null=True)),
                ('tagged_source', models.TextField(blank=True, null=True)),
                ('coded_brace_pattern', models.TextField(blank=True, null=True)),
                ('coded_ids_sequence', models.TextField(blank=True, null=True)),
                ('target_tags', models.TextField(blank=True, null=True)),
                ('okapi_ref_segment_id', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_workspace_okapi.translationstatus')),
                ('text_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_unit_segment_set', to='ai_workspace_okapi.textunit')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MT_RawTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt_raw', models.TextField()),
                ('mt_engine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_workspace_okapi.mt_engine')),
                ('segment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_workspace_okapi.segment')),
            ],
        ),
        migrations.CreateModel(
            name='FontSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_size', models.IntegerField()),
                ('ai_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_font_size_set', to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_font_size_set', to='ai_staff.languages')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_comments_set', to='ai_workspace_okapi.segment')),
            ],
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('file', 'job'), name='file + job combination should be unique'),
        ),
    ]
