# Generated by Django 3.2.4 on 2021-10-30 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace_okapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='segment',
            options={'ordering': ['id']},
        ),
    ]
