# Generated by Django 3.2.4 on 2022-04-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace_okapi', '0002_alter_segment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='random_tag_ids',
            field=models.TextField(blank=True, null=True),
        ),
    ]
