# Generated by Django 3.2.12 on 2022-09-13 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_staff', '0003_auto_20220909_1147'),
        ('ai_workspace_okapi', '0003_segment_random_tag_ids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translationstatus',
            options={'verbose_name_plural': 'Translation statuses'},
        ),
        migrations.AddField(
            model_name='mt_rawtranslation',
            name='reverse_string_for_segment',
            field=models.TextField(choices=[('ai_workspace_okapi.segment', 'Segment'), ('ai_workspace_okapi.mergesegment', 'MergeSegment')], default='ai_workspace_okapi.segment'),
        ),
        migrations.AddField(
            model_name='mt_rawtranslation',
            name='task_mt_engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mt_engine_task', to='ai_staff.ailaysasupportedmtpeengines'),
        ),
        migrations.AlterField(
            model_name='mt_rawtranslation',
            name='mt_engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segment_mt_engine', to='ai_staff.ailaysasupportedmtpeengines'),
        ),
        migrations.CreateModel(
            name='SegmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_history', to='ai_workspace_okapi.segment')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segment_status', to='ai_workspace_okapi.translationstatus')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
