# Generated by Django 3.2.12 on 2022-09-29 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_workspace_okapi', '0004_auto_20220913_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mt_rawtranslation',
            name='reverse_string_for_segment',
        ),
        migrations.AddField(
            model_name='segment',
            name='is_merge_start',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='is_merged',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.CreateModel(
            name='MergeSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(blank=True)),
                ('target', models.TextField(blank=True, null=True)),
                ('temp_target', models.TextField(blank=True, null=True)),
                ('coded_source', models.TextField(blank=True, null=True)),
                ('tagged_source', models.TextField(blank=True, null=True)),
                ('coded_brace_pattern', models.TextField(blank=True, null=True)),
                ('coded_ids_sequence', models.TextField(blank=True, null=True)),
                ('random_tag_ids', models.TextField(blank=True, null=True)),
                ('target_tags', models.TextField(blank=True, null=True)),
                ('okapi_ref_segment_id', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segments', models.ManyToManyField(related_name='segments_merge_segments_set', to='ai_workspace_okapi.Segment')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_workspace_okapi.translationstatus')),
                ('text_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_unit_merge_segment_set', to='ai_workspace_okapi.textunit')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
