# Generated by Django 3.2.12 on 2022-11-11 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_workspace_okapi', '0005_auto_20220929_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergesegment',
            name='is_split',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='is_split',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.CreateModel(
            name='SplitSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(blank=True)),
                ('target', models.TextField(blank=True, null=True)),
                ('temp_target', models.TextField(blank=True, null=True)),
                ('coded_source', models.TextField(blank=True, null=True)),
                ('tagged_source', models.TextField(blank=True, null=True)),
                ('coded_brace_pattern', models.TextField(blank=True, null=True)),
                ('coded_ids_sequence', models.TextField(blank=True, null=True)),
                ('random_tag_ids', models.TextField(blank=True, null=True)),
                ('target_tags', models.TextField(blank=True, null=True)),
                ('okapi_ref_segment_id', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_first', models.BooleanField(default=False, null=True)),
                ('is_split', models.BooleanField(default=True, null=True)),
                ('segment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='split_segment_set', to='ai_workspace_okapi.segment')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_workspace_okapi.translationstatus')),
                ('text_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_unit_split_segment_set', to='ai_workspace_okapi.textunit')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MtRawSplitSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt_raw', models.TextField(blank=True, null=True)),
                ('split_segment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mt_raw_split_segment', to='ai_workspace_okapi.splitsegment')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='split_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='split_segment_comments_set', to='ai_workspace_okapi.splitsegment'),
        ),
    ]
