# Generated by Django 3.2.12 on 2023-05-02 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_workspace_okapi', '0006_auto_20221111_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mt_rawtranslation',
            name='segment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seg_mt_raw', to='ai_workspace_okapi.segment'),
        ),
        migrations.CreateModel(
            name='SegmentPageSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_size', models.IntegerField()),
                ('ai_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_default_page_size', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
