# Generated by Django 3.2.12 on 2023-06-20 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0007_documenttype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_workspace_okapi', '0007_auto_20230502_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmenthistory',
            name='split_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='split_segment_history', to='ai_workspace_okapi.splitsegment'),
        ),
        migrations.CreateModel(
            name='SelflearningAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_word', models.CharField(blank=True, max_length=100, null=True)),
                ('edited_word', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selflearning_target', to='ai_staff.languages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SegmentDiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentense_diff_result', models.CharField(blank=True, max_length=3000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('save_type', models.CharField(blank=True, max_length=100, null=True)),
                ('seg_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_difference', to='ai_workspace_okapi.segmenthistory')),
            ],
        ),
    ]
