# Generated by Django 3.2.12 on 2023-06-29 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0007_documenttype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_workspace', '0013_auto_20230620_1045'),
        ('ai_workspace_okapi', '0010_auto_20230627_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=230, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choicelist_lang', to='ai_staff.languages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='selflearningasset',
            name='target_language',
        ),
        migrations.RemoveField(
            model_name='selflearningasset',
            name='user',
        ),
        migrations.AddField(
            model_name='selflearningasset',
            name='choice_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice_list', to='ai_workspace_okapi.choicelists'),
        ),
        migrations.CreateModel(
            name='ChoiceListSelected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choicelist', to='ai_workspace_okapi.choicelists')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choicelist_project', to='ai_workspace.project')),
            ],
            options={
                'unique_together': {('project', 'choice_list')},
            },
        ),
    ]
