# Generated by Django 3.2.12 on 2023-07-06 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace_okapi', '0011_auto_20230629_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicelists',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choicelists',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='selflearningasset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
