# Generated by Django 3.2.12 on 2024-07-17 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_workspace_okapi', '0013_alter_segmentdiff_sentense_diff_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegementOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_options', to='ai_workspace_okapi.segment')),
                ('split_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='split_segment_option', to='ai_workspace_okapi.splitsegment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_by_options', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdaptSegOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revised_segment', models.TextField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=100, null=True)),
                ('selected', models.BooleanField(default=False)),
                ('segment_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_option_adapt', to='ai_workspace_okapi.segementoptions')),
            ],
        ),
    ]
