# Generated by Django 3.2.12 on 2024-07-18 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace_okapi', '0014_adaptsegoptions_segementoptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segementoptions',
            name='segment',
        ),
        migrations.RemoveField(
            model_name='segementoptions',
            name='split_segment',
        ),
        migrations.RemoveField(
            model_name='segementoptions',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdaptSegOptions',
        ),
        migrations.DeleteModel(
            name='SegementOptions',
        ),
    ]
