# Generated by Django 3.2.12 on 2024-07-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace_okapi', '0015_auto_20240718_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='term_extraction_done',
            field=models.BooleanField(default=False),
        ),
    ]
