# Generated by Django 3.2.12 on 2024-07-30 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace_okapi', '0016_document_term_extraction_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='term_extraction_done',
        ),
    ]
