# Generated by Django 3.2.12 on 2024-07-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace_okapi', '0017_remove_document_term_extraction_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='mt_llm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='mt_llm_glossary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
