# Generated by Django 3.2.12 on 2024-08-05 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace_okapi', '0018_auto_20240731_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='mt_llm',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='mt_llm_glossary',
        ),
    ]
