# Generated by Django 3.2.12 on 2024-08-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace_okapi', '0019_auto_20240805_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt_rawtranslation',
            name='mt_glossary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mt_rawtranslation',
            name='mt_llm_glossary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
