# Generated by Django 3.2.12 on 2024-08-09 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace_okapi', '0020_auto_20240806_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mt_rawtranslation',
            old_name='mt_glossary',
            new_name='mt_only',
        ),
    ]
