# Generated by Django 3.2.12 on 2024-08-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace_okapi', '0021_rename_mt_glossary_mt_rawtranslation_mt_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mt_rawtranslation',
            name='mt_llm_glossary',
        ),
        migrations.AddField(
            model_name='mtrawsplitsegment',
            name='mt_only',
            field=models.TextField(blank=True, null=True),
        ),
    ]
