# Generated by Django 3.2.12 on 2024-08-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace_okapi', '0022_auto_20240812_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentdiff',
            name='diff_corrected',
            field=models.TextField(blank=True, null=True),
        ),
    ]
