# Generated by Django 3.2.12 on 2024-08-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace_okapi', '0023_segmentdiff_diff_corrected'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentdiff',
            name='target_tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
