# Generated by Django 3.2.12 on 2025-04-28 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace_okapi', '0024_segmentdiff_target_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergedTextUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_para', models.TextField()),
                ('temp_para', models.TextField(blank=True)),
                ('translated_para', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_workspace_okapi.textunit')),
            ],
        ),
    ]
