# Generated by Django 3.2.12 on 2025-04-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace_okapi', '0025_mergedtextunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergedtextunit',
            name='tagged_para',
            field=models.TextField(blank=True),
        ),
    ]
