# Generated by Django 3.2.12 on 2025-05-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace_okapi', '0026_mergedtextunit_tagged_para'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergedtextunit',
            name='stage_02',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mergedtextunit',
            name='stage_03',
            field=models.TextField(blank=True, null=True),
        ),
    ]
