# Generated by Django 3.2.12 on 2022-11-11 15:53

import ai_qa.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_workspace', '0008_auto_20221019_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forbidden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forbidden_file', models.FileField(upload_to=ai_qa.models.Forbidden.forbidden_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])])),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_forbidden_file', to='ai_workspace.job')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proj_forbidden_file', to='ai_workspace.project')),
            ],
        ),
        migrations.CreateModel(
            name='Untranslatable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('untranslatable_file', models.FileField(upload_to=ai_qa.models.Untranslatable.untranslatable_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])])),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_untranslatable_file', to='ai_workspace.job')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proj_untranslatable_file', to='ai_workspace.project')),
            ],
        ),
        migrations.CreateModel(
            name='UntranslatableWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='untranslatable_word_file', to='ai_qa.untranslatable')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='untrans_word_job', to='ai_workspace.job')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='untrans_word_proj', to='ai_workspace.project')),
            ],
        ),
        migrations.CreateModel(
            name='ForbiddenWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forbidden_word_file', to='ai_qa.forbidden')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word_job', to='ai_workspace.job')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word_proj', to='ai_workspace.project')),
            ],
        ),
    ]
