# Generated by Django 3.2.12 on 2022-12-14 15:28

import ai_tm.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_workspace', '0009_auto_20221214_1527'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TmxFileNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmx_file', models.FileField(upload_to=ai_tm.models.tmx_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['tmx'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tmx_file_job', to='ai_workspace.job')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tmx_file_project', to='ai_workspace.project')),
            ],
        ),
        migrations.CreateModel(
            name='WordCountGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_words', models.IntegerField(blank=True, default=0, null=True)),
                ('repetition', models.IntegerField(blank=True, default=0, null=True)),
                ('cross_file_rep', models.IntegerField(blank=True, default=0, null=True)),
                ('tm_100', models.IntegerField(blank=True, default=0, null=True)),
                ('tm_95_99', models.IntegerField(blank=True, default=0, null=True)),
                ('tm_85_94', models.IntegerField(blank=True, default=0, null=True)),
                ('tm_75_84', models.IntegerField(blank=True, default=0, null=True)),
                ('tm_50_74', models.IntegerField(blank=True, default=0, null=True)),
                ('tm_101', models.IntegerField(blank=True, default=0, null=True)),
                ('tm_102', models.IntegerField(blank=True, default=0, null=True)),
                ('raw_total', models.IntegerField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_wc_general', to='ai_workspace.project')),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_wc_general', to='ai_workspace.task')),
            ],
        ),
        migrations.CreateModel(
            name='WordCountTmxDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmx_file_obj_id', models.IntegerField(blank=True, null=True)),
                ('tmx_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tmx_file_included', to='ai_tm.tmxfilenew')),
                ('word_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wc_general', to='ai_tm.wordcountgeneral')),
            ],
        ),
        migrations.CreateModel(
            name='UserDefinedRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tm_100_percentage', models.IntegerField(blank=True, default=30, null=True)),
                ('tm_95_99_percentage', models.IntegerField(blank=True, default=60, null=True)),
                ('tm_85_94_percentage', models.IntegerField(blank=True, default=60, null=True)),
                ('tm_75_84_percentage', models.IntegerField(blank=True, default=60, null=True)),
                ('tm_50_74_percentage', models.IntegerField(blank=True, default=100, null=True)),
                ('tm_101_percentage', models.IntegerField(blank=True, default=30, null=True)),
                ('tm_102_percentage', models.IntegerField(blank=True, default=30, null=True)),
                ('tm_repetition_percentage', models.IntegerField(blank=True, default=30, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_default', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CharCountGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_words', models.IntegerField(blank=True, default=0, null=True)),
                ('repetition', models.IntegerField(blank=True, default=0, null=True)),
                ('cross_file_rep', models.IntegerField(blank=True, default=0, null=True)),
                ('tm_100', models.IntegerField(blank=True, default=0, null=True)),
                ('tm_95_99', models.IntegerField(blank=True, default=0, null=True)),
                ('tm_85_94', models.IntegerField(blank=True, default=0, null=True)),
                ('tm_75_84', models.IntegerField(blank=True, default=0, null=True)),
                ('tm_50_74', models.IntegerField(blank=True, default=0, null=True)),
                ('tm_101', models.IntegerField(blank=True, default=0, null=True)),
                ('tm_102', models.IntegerField(blank=True, default=0, null=True)),
                ('raw_total', models.IntegerField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_cc_general', to='ai_workspace.project')),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_cc_general', to='ai_workspace.task')),
            ],
        ),
    ]
