# Generated by Django 3.2.12 on 2023-09-30 20:20

import ai_imagetranslation.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_workspace', '0014_auto_20230930_1725'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_staff', '0009_designerorientation_designshape_designshapecategory_fontcatagorylist_fontdata_fontfamily_fontlanguag'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIimageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_category', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AspectRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='aspect-ratio')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundRemovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_json_id', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('canvas_json', models.JSONField(blank=True, null=True)),
                ('original_image', models.FileField(blank=True, null=True, upload_to=ai_imagetranslation.models.user_directory_path_image_background_removel)),
                ('image', models.FileField(blank=True, null=True, upload_to=ai_imagetranslation.models.user_directory_path_image_background_removel)),
                ('mask', models.FileField(blank=True, null=True, upload_to=ai_imagetranslation.models.user_directory_path_image_background_removel)),
                ('eraser_transparent_mask', models.FileField(blank=True, null=True, upload_to=ai_imagetranslation.models.user_directory_path_image_background_removel)),
                ('preview_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bgremoval_created_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='custom_image_gen')),
            ],
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composition_name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='custom_image_gen')),
            ],
        ),
        migrations.CreateModel(
            name='CustomImageGenerationStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='custom_image_gen')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralPromptList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imageload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to=ai_imagetranslation.models.user_directory_path_image_load, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'jpeg', 'jpg', 'png'])])),
                ('file_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('types', models.CharField(blank=True, max_length=10, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to=ai_imagetranslation.models.user_directory_path_image_load_thumbnail)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageStyleSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='custom_image_gen')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('default_prompt', models.CharField(blank=True, max_length=700, null=True)),
                ('negative_prompt', models.CharField(blank=True, max_length=700, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageTranslate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to=ai_imagetranslation.models.user_directory_path_image_translate_image)),
                ('file_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('types', models.CharField(blank=True, max_length=10, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('mask', models.FileField(blank=True, null=True, upload_to=ai_imagetranslation.models.user_directory_path_image_translate_process)),
                ('mask_json', models.JSONField(blank=True, null=True)),
                ('inpaint_image', models.FileField(blank=True, null=True, upload_to=ai_imagetranslation.models.user_directory_path_image_translate_result)),
                ('create_inpaint_pixel_location', models.FileField(blank=True, null=True, upload_to=ai_imagetranslation.models.user_directory_path_image_translate_process)),
                ('source_canvas_json', models.JSONField(blank=True, null=True)),
                ('source_bounding_box', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to=ai_imagetranslation.models.user_directory_path_image_load_thumbnail)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagetranslate_created_by', to=settings.AUTH_USER_MODEL)),
                ('image_load', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='s_lang', to='ai_imagetranslation.imageload')),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_translate_project', to='ai_workspace.project')),
                ('source_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s_lang', to='ai_staff.languageslocale')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lighting_name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='custom_image_gen')),
            ],
        ),
        migrations.CreateModel(
            name='StableDiffusionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(blank=True, max_length=200, null=True)),
                ('cfg', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StableDiffusionAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_image', models.FileField(blank=True, null=True, upload_to='stable-diffusion-image-gen')),
                ('image', models.FileField(blank=True, null=True, upload_to='stable-diffusion-image')),
                ('used_api', models.CharField(blank=True, max_length=200, null=True)),
                ('model_name', models.CharField(blank=True, max_length=200, null=True)),
                ('prompt', models.CharField(blank=True, max_length=3000, null=True)),
                ('negative_prompt', models.CharField(blank=True, max_length=3000, null=True)),
                ('style', models.CharField(blank=True, max_length=100, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('steps', models.IntegerField(blank=True, null=True)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='stable-diffusion-image-thumbnail')),
                ('celery_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stable_diff_created_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SDImageResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(blank=True, max_length=200, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('steps', models.IntegerField(blank=True, null=True)),
                ('sd_image_resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sd_image_res', to='ai_imagetranslation.aspectratio')),
            ],
        ),
        migrations.CreateModel(
            name='ImageTranslateResizeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resize_image', models.FileField(blank=True, null=True, upload_to=ai_imagetranslation.models.user_directory_path_image_translate_image_temp_resize)),
                ('resize_mask', models.FileField(blank=True, null=True, upload_to=ai_imagetranslation.models.user_directory_path_image_translate_image_temp_resize)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('image_translate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_translate_resize', to='ai_imagetranslation.imagetranslate')),
            ],
        ),
        migrations.CreateModel(
            name='ImageStyleCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_category_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('style_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style', to='ai_imagetranslation.customimagegenerationstyle')),
            ],
        ),
        migrations.CreateModel(
            name='ImageModificationTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_style_name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='custom_image_gen')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('default_prompt', models.CharField(blank=True, max_length=700, null=True)),
                ('custom_image_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_category', to='ai_imagetranslation.imagestylecategories')),
            ],
        ),
        migrations.CreateModel(
            name='ImageInpaintCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_canvas_json', models.JSONField(blank=True, null=True)),
                ('target_bounding_box', models.JSONField(blank=True, null=True)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to=ai_imagetranslation.models.user_directory_path_image_translate_thumbnail)),
                ('export', models.FileField(blank=True, null=True, upload_to=ai_imagetranslation.models.user_directory_path_image_translate_export)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('create_inpaint_pixel_location', models.FileField(blank=True, null=True, upload_to=ai_imagetranslation.models.user_directory_path_image_translate_process_target)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_translation_job', to='ai_workspace.job')),
                ('source_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s_im', to='ai_imagetranslation.imagetranslate')),
                ('source_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s_lang_inpaint', to='ai_staff.languageslocale')),
                ('target_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_lang', to='ai_staff.languageslocale')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BackgroundRemovePreviewimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('back_ground_remove', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='back_ground_rm_preview_im', to='ai_imagetranslation.backgroundremovel')),
            ],
        ),
    ]
