# Generated by Django 3.2.12 on 2024-06-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_imagetranslation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stablediffusionapi',
            name='negative_prompt_mt',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='stablediffusionapi',
            name='prompt_mt',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
