# Generated by Django 3.2.12 on 2023-02-24 06:23

import ai_openai.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_staff', '0006_auto_20230224_0622'),
        ('ai_workspace', '0010_auto_20230224_0622'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_string', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('response_copies', models.IntegerField(blank=True, default=1, null=True)),
                ('product_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('product_name_mt', models.CharField(blank=True, max_length=1000, null=True)),
                ('keywords', models.CharField(blank=True, max_length=1000, null=True)),
                ('description_mt', models.TextField(blank=True, null=True)),
                ('keywords_mt', models.TextField(blank=True, null=True)),
                ('prompt_string_mt', models.TextField(blank=True, null=True)),
                ('response_charecter_limit', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Tone', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_tone', to='ai_staff.prompttones')),
                ('catagories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_staff.promptcategories')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_doc', to='ai_workspace.mydocuments')),
                ('model_gpt_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gpt_model', to='ai_staff.modelgptname')),
                ('source_prompt_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_lang', to='ai_staff.languages')),
                ('sub_catagories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_staff.promptsubcategories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AiPromptCustomize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_text', models.TextField(blank=True, null=True)),
                ('user_text_mt', models.TextField(blank=True, null=True)),
                ('credits_used', models.IntegerField(blank=True, null=True)),
                ('api_result', models.TextField(blank=True, null=True)),
                ('prompt_generated', models.TextField(blank=True, null=True)),
                ('prompt_result', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_cust', to='ai_staff.aicustomize')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_doc', to='ai_workspace.mydocuments')),
                ('tone', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customize_tone', to='ai_staff.prompttones')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_text_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_lang', to='ai_staff.languages')),
            ],
        ),
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input_token', models.CharField(blank=True, max_length=10, null=True)),
                ('prompt_tokens', models.CharField(blank=True, max_length=10, null=True)),
                ('total_tokens', models.CharField(blank=True, max_length=10, null=True)),
                ('completion_tokens', models.CharField(blank=True, max_length=10, null=True)),
                ('no_of_outcome', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranslateCustomizeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_used', models.IntegerField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customization', to='ai_openai.aipromptcustomize')),
                ('mt_engine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customization_mt_engine', to='ai_staff.ailaysasupportedmtpeengines')),
                ('target_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_lang', to='ai_staff.languages')),
            ],
        ),
        migrations.CreateModel(
            name='TextgeneratedCreditDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_to_deduce', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageGeneratorPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(blank=True, null=True)),
                ('prompt_mt', models.TextField(blank=True, null=True)),
                ('credits_used', models.IntegerField(blank=True, null=True)),
                ('no_of_image', models.IntegerField(blank=True, null=True)),
                ('image_resolution', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ai_staff.imagegeneratorresolution')),
            ],
        ),
        migrations.CreateModel(
            name='ImageGenerationPromptResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_id', models.CharField(blank=True, max_length=50, null=True)),
                ('generated_image', models.FileField(upload_to=ai_openai.models.user_directory_path_image_gen_result)),
                ('image_generator_prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gen_img', to='ai_openai.imagegeneratorprompt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AiPromptResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_id', models.CharField(blank=True, max_length=50, null=True)),
                ('copy', models.IntegerField(blank=True, null=True)),
                ('response_created', models.CharField(blank=True, max_length=50, null=True)),
                ('prompt_generated', models.TextField(blank=True, null=True)),
                ('api_result', models.TextField(blank=True, null=True)),
                ('translated_prompt_result', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_prompt', to='ai_openai.aiprompt')),
                ('result_lang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_result_lang_src', to='ai_staff.languages')),
                ('start_phrase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_staff.promptstartphrases')),
                ('token_usage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_tokens', to='ai_openai.tokenusage')),
            ],
        ),
    ]
