# Generated by Django 3.2.12 on 2023-03-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_openai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegeneratorprompt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
