# Generated by Django 3.2.12 on 2023-03-27 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_exportpdf', '0003_ai_pdfupload_created_by'),
        ('ai_workspace', '0011_expresstaskhistory'),
        ('ai_openai', '0002_imagegeneratorprompt_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprompt',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiprompt',
            name='pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_pdf', to='ai_exportpdf.ai_pdfupload'),
        ),
        migrations.AddField(
            model_name='aiprompt',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_task', to='ai_workspace.task'),
        ),
        migrations.AddField(
            model_name='aipromptcustomize',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customize_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aipromptcustomize',
            name='pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_pdf', to='ai_exportpdf.ai_pdfupload'),
        ),
        migrations.AddField(
            model_name='aipromptcustomize',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_task', to='ai_workspace.task'),
        ),
        migrations.AddField(
            model_name='imagegenerationpromptresponse',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='img_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
