# Generated by Django 3.2.12 on 2023-05-02 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_workspace', '0012_auto_20230502_1205'),
        ('ai_staff', '0007_documenttype'),
        ('ai_openai', '0003_auto_20230327_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_title', models.CharField(blank=True, max_length=100, null=True)),
                ('user_title_mt', models.CharField(blank=True, max_length=100, null=True)),
                ('keywords', models.CharField(blank=True, max_length=1000, null=True)),
                ('keywords_mt', models.CharField(blank=True, max_length=1000, null=True)),
                ('prompt_user_title_mt', models.CharField(blank=True, max_length=200, null=True)),
                ('prompt_keyword_mt', models.CharField(blank=True, max_length=200, null=True)),
                ('response_copies_keyword', models.IntegerField(blank=True, default=10, null=True)),
                ('steps', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_categories', to='ai_staff.promptcategories')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_created_by', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_doc', to='ai_workspace.mydocuments')),
                ('sub_categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_sub_categories', to='ai_staff.promptsubcategories')),
                ('tone', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_tone', to='ai_staff.prompttones')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_test_lang_src', to='ai_staff.languages')),
            ],
        ),
        migrations.CreateModel(
            name='BlogOutline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_selected_title', models.TextField(blank=True, null=True)),
                ('user_selected_title_mt', models.TextField(blank=True, null=True)),
                ('selected_group_num', models.IntegerField(blank=True, null=True)),
                ('response_copies', models.IntegerField(blank=True, default=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blogtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.TextField(blank=True, null=True)),
                ('blog_title_mt', models.TextField(blank=True, null=True)),
                ('selected_field', models.BooleanField(blank=True, null=True)),
                ('response_copies', models.IntegerField(blank=True, default=3, null=True)),
                ('blog_creation_gen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_title_create', to='ai_openai.blogcreation')),
                ('sub_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_title_sub_categories', to='ai_staff.promptsubcategories')),
                ('token_usage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogtitle_used_tokens', to='ai_openai.tokenusage')),
            ],
        ),
        migrations.CreateModel(
            name='BlogOutlineSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_outline', models.TextField(blank=True, null=True)),
                ('blog_outline_mt', models.TextField(blank=True, null=True)),
                ('selected_field', models.BooleanField(blank=True, default=False, null=True)),
                ('custom_order', models.IntegerField(blank=True, null=True)),
                ('temp_order', models.IntegerField(blank=True, null=True)),
                ('group', models.IntegerField(blank=True, null=True)),
                ('blog_outline_gen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_outline_session', to='ai_openai.blogoutline')),
                ('blog_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogoutlinesession_title', to='ai_openai.blogtitle')),
            ],
        ),
        migrations.AddField(
            model_name='blogoutline',
            name='blog_title_gen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogoutline_title', to='ai_openai.blogtitle'),
        ),
        migrations.AddField(
            model_name='blogoutline',
            name='sub_categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_outline_sub_categories', to='ai_staff.promptsubcategories'),
        ),
        migrations.AddField(
            model_name='blogoutline',
            name='token_usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogoutline_used_tokens', to='ai_openai.tokenusage'),
        ),
        migrations.CreateModel(
            name='BlogKeywordGenerate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_keyword', models.CharField(blank=True, max_length=200, null=True)),
                ('blog_keyword_mt', models.CharField(blank=True, max_length=200, null=True)),
                ('selected_field', models.BooleanField(blank=True, null=True)),
                ('blog_creation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_key_create', to='ai_openai.blogcreation')),
                ('token_usage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_creation_used_tokens', to='ai_openai.tokenusage')),
            ],
        ),
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_article', models.TextField(blank=True, null=True)),
                ('blog_article_mt', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog_creation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_article_create', to='ai_openai.blogcreation')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_doc_blog', to='ai_workspace.mydocuments')),
                ('sub_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_article_sub_categories', to='ai_staff.promptsubcategories')),
                ('token_usage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogarticle_used_tokens', to='ai_openai.tokenusage')),
            ],
        ),
    ]
