# Generated by Django 3.2.12 on 2023-06-20 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0007_documenttype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_workspace', '0013_auto_20230620_1045'),
        ('ai_openai', '0004_auto_20230502_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_doc_blog', to='ai_workspace.mydocuments'),
        ),
        migrations.AlterField(
            model_name='blogcreation',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_doc', to='ai_workspace.mydocuments'),
        ),
        migrations.CreateModel(
            name='CustomizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('append', models.BooleanField(default=True)),
                ('new_line', models.BooleanField(default=True)),
                ('mt_engine', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customization_mt_engine_setting', to='ai_staff.ailaysasupportedmtpeengines')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_setting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
