# Generated by Django 3.2.12 on 2023-10-12 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0010_auto_20231012_1436'),
        ('ai_workspace', '0014_auto_20230930_1725'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_openai', '0005_auto_20230620_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_content', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('html_data', models.TextField(blank=True, null=True)),
                ('generated_content_mt', models.TextField(blank=True, null=True)),
                ('selected_field', models.BooleanField(blank=True, null=True)),
                ('response_copies', models.IntegerField(blank=True, default=1, null=True)),
                ('custom_order', models.IntegerField(blank=True, null=True)),
                ('temp_order', models.IntegerField(blank=True, null=True)),
                ('group', models.IntegerField(blank=True, null=True)),
                ('body_matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_body_matter', to='ai_staff.bodymatter')),
            ],
        ),
        migrations.CreateModel(
            name='BookCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_mt', models.TextField(blank=True, null=True)),
                ('author_info', models.TextField(blank=True, null=True)),
                ('author_info_mt', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('title_mt', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_lang_src', to='ai_staff.languages')),
                ('categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_categories', to='ai_staff.promptcategories')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_created_by', to=settings.AUTH_USER_MODEL)),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_genre', to='ai_staff.genre')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_level', to='ai_staff.levels')),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_create_project', to='ai_workspace.project')),
                ('sub_categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_sub_categories', to='ai_staff.promptsubcategories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_data', models.TextField(blank=True, null=True)),
                ('book_title', models.TextField(blank=True, null=True)),
                ('book_title_mt', models.TextField(blank=True, null=True)),
                ('selected_field', models.BooleanField(blank=True, null=True)),
                ('response_copies', models.IntegerField(blank=True, default=3, null=True)),
                ('book_creation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_title_create', to='ai_openai.bookcreation')),
                ('sub_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_title_sub_categories', to='ai_staff.promptsubcategories')),
                ('token_usage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booktitle_used_tokens', to='ai_openai.tokenusage')),
            ],
        ),
        migrations.CreateModel(
            name='BookFrontMatter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_data', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('generated_content', models.TextField(blank=True, null=True)),
                ('generated_content_mt', models.TextField(blank=True, null=True)),
                ('selected_field', models.BooleanField(blank=True, null=True)),
                ('custom_order', models.IntegerField(blank=True, null=True)),
                ('temp_order', models.IntegerField(blank=True, null=True)),
                ('book_creation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_fm_create', to='ai_openai.bookcreation')),
                ('front_matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_front_matter', to='ai_staff.frontmatter')),
                ('sub_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_fm_sub_categories', to='ai_staff.promptsubcategories')),
                ('token_usage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_fm_tokens', to='ai_openai.tokenusage')),
            ],
        ),
        migrations.CreateModel(
            name='BookBodyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_data', models.TextField(blank=True, null=True)),
                ('generated_chapter', models.TextField(blank=True, null=True)),
                ('generated_chapter_mt', models.TextField(blank=True, null=True)),
                ('chapter_summary', models.TextField(blank=True, null=True)),
                ('book_bm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_bdy_det_create', to='ai_openai.bookbody')),
                ('token_usage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookbdy_det_tokens', to='ai_openai.tokenusage')),
            ],
        ),
        migrations.AddField(
            model_name='bookbody',
            name='book_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_bdy_create', to='ai_openai.bookcreation'),
        ),
        migrations.AddField(
            model_name='bookbody',
            name='book_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_title_bdy', to='ai_openai.booktitle'),
        ),
        migrations.AddField(
            model_name='bookbody',
            name='sub_categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_bdy_sub_categories', to='ai_staff.promptsubcategories'),
        ),
        migrations.AddField(
            model_name='bookbody',
            name='token_usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookbdy_tokens', to='ai_openai.tokenusage'),
        ),
        migrations.CreateModel(
            name='BookBackMatter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('html_data', models.TextField(blank=True, null=True)),
                ('generated_content', models.TextField(blank=True, null=True)),
                ('generated_content_mt', models.TextField(blank=True, null=True)),
                ('selected_field', models.BooleanField(blank=True, null=True)),
                ('custom_order', models.IntegerField(blank=True, null=True)),
                ('temp_order', models.IntegerField(blank=True, null=True)),
                ('back_matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_back_matter', to='ai_staff.backmatter')),
                ('book_creation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_bm_create', to='ai_openai.bookcreation')),
                ('sub_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_bm_sub_categories', to='ai_staff.promptsubcategories')),
                ('token_usage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_bm_tokens', to='ai_openai.tokenusage')),
            ],
        ),
        migrations.AddField(
            model_name='aiprompt',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_prompt', to='ai_openai.bookcreation'),
        ),
        migrations.AddField(
            model_name='aipromptcustomize',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_book', to='ai_openai.bookcreation'),
        ),
    ]
