# Generated by Django 3.2.12 on 2023-11-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_openai', '0006_auto_20231012_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('news_modify_name', models.CharField(blank=True, max_length=200, null=True)),
                ('prompt', models.CharField(blank=True, max_length=900, null=True)),
                ('assistant', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
