# Generated by Django 3.2.12 on 2023-12-13 07:44

import ai_openai.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_workspace', '0018_alter_projectfilescreatetype_file_create_type'),
        ('ai_staff', '0011_promptstartphrases_assistant'),
        ('ai_openai', '0007_newsprompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPromptDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_words', models.CharField(blank=True, max_length=100, null=True)),
                ('name_of_the_speaker', models.CharField(blank=True, max_length=100, null=True)),
                ('position_of_the_speaker', models.CharField(blank=True, max_length=100, null=True)),
                ('place_of_the_speech', models.CharField(blank=True, max_length=100, null=True)),
                ('aiprompt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_prompt_news_details', to='ai_openai.aiprompt')),
            ],
        ),
        migrations.CreateModel(
            name='NewsTranscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to=ai_openai.models.user_directory_news_transcribe)),
                ('audio_len', models.CharField(blank=True, max_length=150, null=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_audio_lang', to='ai_staff.languages')),
                ('prompt_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_transcribe', to='ai_staff.promptsubcategories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewsTranscribeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcribe_result', models.TextField(blank=True, null=True)),
                ('transcribed_news_report', models.TextField(blank=True, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_transcribe_doc', to='ai_workspace.mydocuments')),
                ('news_transcribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_transcribe', to='ai_openai.newstranscribe')),
            ],
        ),
        migrations.DeleteModel(
            name='NewsPrompt',
        ),
    ]
