# Generated by Django 3.2.12 on 2024-02-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_openai', '0008_auto_20231213_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookbody',
            name='sub_headings',
            field=models.TextField(blank=True, null=True),
        ),
    ]
