# Generated by Django 3.2.12 on 2024-07-08 12:34

import ai_openai.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0019_auto_20240111_1221'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_openai', '0009_bookbody_sub_headings'),
    ]

    operations = [
        migrations.CreateModel(
            name='LangscapeOcrPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_document', models.FileField(blank=True, null=True, upload_to=ai_openai.models.user_directory_langscape_ocr_document)),
                ('prof_reading_doc', models.FileField(blank=True, null=True, upload_to=ai_openai.models.user_directory_langscape_ocr_PR_document)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_for_ocr', to='ai_workspace.mydocuments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
