# Generated by Django 3.2.12 on 2024-07-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_openai', '0010_langscapeocrpr'),
    ]

    operations = [
        migrations.AddField(
            model_name='langscapeocrpr',
            name='file_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
