# Generated by Django 3.2.12 on 2024-09-16 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_openai', '0013_brandvoice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BrandVoice',
            new_name='MyStyle',
        ),
        migrations.AddField(
            model_name='aipromptcustomize',
            name='my_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_style', to='ai_openai.mystyle'),
        ),
    ]
