# Generated by Django 3.2.12 on 2024-09-17 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_openai', '0014_auto_20240916_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aipromptcustomize',
            name='my_style',
        ),
    ]
