# Generated by Django 3.2.12 on 2024-09-17 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_openai', '0015_remove_aipromptcustomize_my_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='aipromptcustomize',
            name='my_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_style', to='ai_openai.mystyle'),
        ),
    ]
