# Generated by Django 3.2.12 on 2024-09-17 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0022_alter_aicustomize_prompt'),
        ('ai_openai', '0016_aipromptcustomize_my_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aipromptcustomize',
            name='customize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_cust', to='ai_staff.aicustomize'),
        ),
    ]
