# Generated by Django 3.2.4 on 2022-02-16 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import integerations.gitlab_.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitlabApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_token', models.CharField(max_length=255, validators=[integerations.gitlab_.models.GitlabApp.validate_oauth_token])),
                ('username', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('accessed_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('ai_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('assign_task', 'Assign task'),),
            },
        ),
        migrations.AddConstraint(
            model_name='gitlabapp',
            constraint=models.UniqueConstraint(fields=('ai_user', 'username'), name='Duplicate gitlab usernames not allowed for one ai-user ...'),
        ),
    ]
