# Generated by Django 3.2.4 on 2022-02-17 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gitlab_', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_name', models.TextField()),
                ('repository_fullname', models.TextField()),
                ('is_localize_registered', models.BooleanField(default=False)),
                ('is_alive_in_github', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('accessed_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('gitlab_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gitlab_repository_set', to='gitlab_.gitlabapp')),
            ],
            options={
                'permissions': (('owner_repository', 'Owner'),),
            },
        ),
        migrations.CreateModel(
            name='FetchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_fetched_on', models.DateTimeField(auto_now=True)),
                ('github_token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gitlab_fetch_info', to='gitlab_.gitlabapp')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
