# Generated by Django 3.2.4 on 2022-02-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitlab_', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitlabapp',
            name='oauth_token',
            field=models.CharField(max_length=255),
        ),
    ]
