# Generated by Django 3.2.4 on 2022-02-17 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitlab_', '0002_alter_gitlabapp_oauth_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gitlabapp',
            options={},
        ),
    ]
