# Generated by Django 3.2.4 on 2022-02-21 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0022_alter_taskdetails_options'),
        ('controller', '0001_initial'),
        ('gitlab_', '0003_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_localize_registered', models.BooleanField(default=False)),
                ('file', models.CharField(max_length=255)),
                ('file_path', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('accessed_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_contentfiles_set', to='gitlab_.branch')),
                ('controller', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gitlab_contentfile', to='controller.filecontroller')),
                ('uploaded_file', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gitlab_contentfile', to='ai_workspace.file')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
