# Generated by Django 3.2.4 on 2022-02-21 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
        ('ai_workspace', '0022_alter_taskdetails_options'),
        ('gitlab_', '0004_contentfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_hash', models.TextField(null=True)),
                ('controller', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controller_gitlab_downloadproject', to='controller.downloadcontroller')),
                ('project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_gitlab_downloadproject', to='ai_workspace.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
