# Generated by Django 3.2.4 on 2022-06-16 14:52

import ai_pay.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_staff', '0006_currencybasedoncountry_mtlanguagelocalevoicesupport_mtlanguagesupport_projecttype_projecttypedetail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.CharField(blank=True, max_length=191, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poid', models.CharField(default=ai_pay.models.PurchaseOrder.generate_po_id, max_length=50, unique=True)),
                ('po_status', models.CharField(choices=[('draft', 'draft'), ('issued', 'issued'), ('open', 'open'), ('closed', 'closed'), ('void', 'void')], default='draft', max_length=50)),
                ('po_file', models.FileField(blank=True, null=True, upload_to=ai_pay.models.po_dir_path)),
                ('po_total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_assign', to='ai_pay.poassignment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_client', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_currency', to='ai_staff.currencies')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='POTaskDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=191)),
                ('project_name', models.CharField(blank=True, max_length=223, null=True)),
                ('projectid', models.CharField(blank=True, max_length=223, null=True)),
                ('word_count', models.IntegerField(blank=True, null=True)),
                ('char_count', models.IntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_po', to='ai_pay.poassignment')),
                ('source_language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_source_lang', to='ai_staff.languages')),
                ('target_language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_target_lang', to='ai_staff.languages')),
                ('unit_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_unit', to='ai_staff.servicetypeunits')),
            ],
        ),
        migrations.CreateModel(
            name='AilaysaGeneratedInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoid', models.CharField(default=ai_pay.models.AilaysaGeneratedInvoice.generate_invo_id, max_length=50, unique=True)),
                ('invo_status', models.CharField(choices=[('draft', 'draft'), ('paid', 'paid'), ('open', 'open'), ('void', 'void')], max_length=50)),
                ('invo_file', models.FileField(blank=True, null=True, upload_to=ai_pay.models.invoice_dir_path)),
                ('gst', models.CharField(choices=[('NOGST', 'NOGST'), ('SGST,CGST', 'SGST,CGST'), ('IGST', 'IGST')], max_length=50)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_client_invo', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ai_invo_currency', to='ai_staff.currencies')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_seller_invo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AiInvoicePO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_invo_po', to='ai_pay.ailaysageneratedinvoice')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_po', to='ai_pay.purchaseorder')),
            ],
        ),
    ]
