# Generated by Django 3.2.4 on 2022-06-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_pay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ailaysageneratedinvoice',
            name='grand_total',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ailaysageneratedinvoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ailaysageneratedinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='potaskdetails',
            name='total_amount',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='potaskdetails',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_total_amount',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
