# Generated by Django 3.2.4 on 2022-08-11 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0006_currencybasedoncountry_mtlanguagelocalevoicesupport_mtlanguagesupport_projecttype_projecttypedetail'),
        ('ai_pay', '0002_auto_20220621_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potaskdetails',
            name='unit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_unit', to='ai_staff.billingunits'),
        ),
    ]
