# Generated by Django 3.2.12 on 2022-09-13 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0005_auto_20220913_1011'),
        ('ai_pay', '0003_alter_potaskdetails_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='poassignment',
            name='step',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='po_assignment_step', to='ai_workspace.steps'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='potaskdetails',
            name='estimated_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='potaskdetails',
            name='po',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_task', to='ai_pay.purchaseorder'),
        ),
        migrations.AddField(
            model_name='potaskdetails',
            name='tsk_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
