# Generated by Django 3.2.12 on 2022-10-19 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0004_transcribesupportedpunctuation'),
        ('ai_pay', '0004_auto_20220913_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeSupportedCountries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_countries', to='ai_staff.countries')),
            ],
        ),
    ]
