# Generated by Django 3.2.12 on 2022-11-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_pay', '0005_stripesupportedcountries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_status',
            field=models.CharField(choices=[('draft', 'draft'), ('issued', 'issued'), ('open', 'open'), ('closed', 'closed'), ('void', 'void'), ('generated', 'generated')], default='draft', max_length=50),
        ),
    ]
