# Generated by Django 3.2.12 on 2023-06-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_pay', '0006_alter_purchaseorder_po_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='potaskdetails',
            name='assign_status',
            field=models.CharField(blank=True, choices=[('task_accepted', 'task_accepted'), ('change_request', 'change_request')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='potaskdetails',
            name='reassigned',
            field=models.BooleanField(default=False),
        ),
    ]
