# Generated by Django 3.2.12 on 2023-06-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_pay', '0007_auto_20230620_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='potaskdetails',
            name='task_uid',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
