null=None
false=False
true=True
canvaswidth=0
canvasheight=0
basic_json =  { "version": "5.3.0",
	"objects": [], 
	"backgroundImage": {
        "type": "rect",
        "version": "5.3.0",
        "originX": "left",
        "originY": "top",
        "left": 0,
        "top": 0,
        "width": canvaswidth,
        "height": canvasheight,
        "fill": "rgba(255,255,255,1)",
        "stroke": null,
        "strokeWidth": 0,
        "strokeDashArray": null,
        "strokeLineCap": "butt",
        "strokeDashOffset": 0,
        "strokeLineJoin": "miter",
        "strokeUniform": false,
        "strokeMiterLimit": 4,
        "scaleX": 1,
        "scaleY": 1,
        "angle": 0,
        "flipX": false,
        "flipY": false,
        "opacity": 1,
        "shadow": {
            "color": "rgba(0,0,0,0.8)",
            "blur": 0.01,
            "offsetX": 0,
            "offsetY": 0,
            "affectStroke": false,
            "nonScaling": false
        },
        "visible": true,
        "backgroundColor": "",
        "fillRule": "nonzero",
        "paintFirst": "fill",
        "globalCompositeOperation": "source-over",
        "skewX": 0,
        "skewY": 0,
        "rx": 0,
        "ry": 0,
        "lockMovementX": false,
        "lockMovementY": false,
        "perPixelTargetFind": false,
        "objectCaching": false
    } 
}


textbox_json={
    "type": "textbox",
    "version": "5.3.0",
    "originX": "left",
    "originY": "top",
    "left": 0,
    "top": 0,
    "width": 0,
    "height": 0,
    "fill": "rgb(0,0,0)",
    "stroke": null,
    "strokeWidth": 1,
    "strokeDashArray": null,
    "strokeLineCap": "butt",
    "strokeDashOffset": 0,
    "strokeLineJoin": "miter",
    "strokeUniform": false,
    "strokeMiterLimit": 4,
    "scaleX": 1,
    "scaleY": 1,
    "angle": 0,
    "flipX": false,
    "flipY": false,
    "opacity": 1,
    "shadow": null,
    "visible": true,
    "backgroundColor": "",
    "fillRule": "nonzero",
    "paintFirst": "fill",
    "globalCompositeOperation": "source-atop",
    "skewX": 0,
    "skewY": 0,
    "fontFamily": "Roboto",
    "fontWeight": "normal",
    "fontSize": 59,
    "text": "",
    "underline": false,
    "overline": false,
    "linethrough": false,
    "textAlign": "left",
    "fontStyle": "normal",
    "lineHeight": 1,
    "textBackgroundColor": "",
    "charSpacing": 0,
    "styles": [],
    "direction": "ltr",
    "path": null,
    "pathStartOffset": 0,
    "pathSide": "left",
    "pathAlign": "baseline",
    "minWidth": 20,
    "splitByGrapheme": false,
    "id": "text-0",
    "hasBorders": true,
    "evented": true,
    "selectable": false,
    "status": "Unconfirmed",
    "lockMovementX": false,
    "lockMovementY": false,
    "editable": true,
    "name": "",
    "breakWords": true,
    "perPixelTargetFind": false,
    "isWrapping": false,
    "objectCaching": true
}


img_json={
    "type": "image",
    "version": "5.3.0",
    "originX": "left",
    "originY": "top",
    "left": 0,
    "top": 0,
    "width": 0,
    "height": 0,
    "fill": "rgb(0,0,0)",
    "stroke": null,
    "strokeWidth": 0,
    "strokeDashArray": null,
    "strokeLineCap": "butt",
    "strokeDashOffset": 0,
    "strokeLineJoin": "miter",
    "strokeUniform": false,
    "strokeMiterLimit": 4,
    "scaleX": 1,
    "scaleY": 1,
    "angle": 0,
    "flipX": false,
    "flipY": false,
    "opacity": 1,
    "shadow": null,
    "visible": true,
    "backgroundColor": "",
    "fillRule": "nonzero",
    "paintFirst": "fill",
    "globalCompositeOperation": "source-atop",
    "skewX": 0,
    "skewY": 0,
    "cropX": 0,
    "cropY": 0,
    "id": "background",
    "hasBorders": true,
    "evented": false,
    "selectable": false,
    "lockMovementX": true,
    "lockMovementY": true,
    "editable": false,
    "name": "Background-current",
    "perPixelTargetFind": false,
    "objectCaching": false,
    "src": "",
    "crossOrigin": "anonymous",
    "filters": [
        {
            "type": "Brightness",
            "brightness": 0
        },
        {
            "type": "Contrast",
            "contrast": 0
        },
        {
            "type": "Saturation",
            "saturation": 0
        },
        {
            "type": "Blur",
            "blur": 0
        },
        {
            "type": "Vibrance",
            "vibrance": 0
        },
        {
            "type": "Noise",
            "noise": 0
        },
        {
            "type": "HueRotation",
            "rotation": 0
        }
    ]
}