# Generated by Django 3.2.12 on 2022-12-14 15:29

import ai_exportpdf.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ai_PdfUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to=ai_exportpdf.models.user_directory_path)),
                ('docx_url_field', models.URLField(blank=True, null=True)),
                ('pdf_file_name', models.CharField(blank=True, max_length=200, null=True)),
                ('pdf_task_id', models.CharField(blank=True, max_length=200, null=True)),
                ('pdf_conversion_sec', models.IntegerField(blank=True, null=True)),
                ('pdf_language', models.CharField(blank=True, max_length=200, null=True)),
                ('pdf_format_option', models.CharField(blank=True, max_length=200, null=True)),
                ('pdf_api_use', models.CharField(blank=True, max_length=200, null=True)),
                ('pdf_no_of_page', models.IntegerField(blank=True, null=True)),
                ('counter', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, default='', null=True)),
                ('docx_file_name', models.CharField(blank=True, max_length=200, null=True)),
                ('file_name', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
