# Generated by Django 3.2.12 on 2023-02-24 06:22

import ai_exportpdf.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0009_auto_20221214_1527'),
        ('ai_exportpdf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ai_pdfupload',
            name='slug',
        ),
        migrations.AddField(
            model_name='ai_pdfupload',
            name='docx_file_from_writer',
            field=models.FileField(blank=True, null=True, upload_to=ai_exportpdf.models.edited_file_path),
        ),
        migrations.AddField(
            model_name='ai_pdfupload',
            name='html_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ai_pdfupload',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdf_task', to='ai_workspace.task'),
        ),
        migrations.AddField(
            model_name='ai_pdfupload',
            name='translation_task_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ai_pdfupload',
            name='updated_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
