# Generated by Django 3.2.12 on 2023-03-27 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_exportpdf', '0002_auto_20230224_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai_pdfupload',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
