# Generated by Django 3.2.12 on 2023-06-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_exportpdf', '0003_ai_pdfupload_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai_pdfupload',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
