# Generated by Django 3.2.12 on 2022-09-29 10:20

import ai_glex.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_workspace', '0007_auto_20220929_0703'),
        ('ai_staff', '0003_auto_20220909_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_glossary_source_name', models.CharField(blank=True, max_length=20, null=True)),
                ('details_of_PGS', models.TextField(blank=True, null=True)),
                ('source_Copyright_owner', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Glossary General Notes')),
                ('usage_permission', models.CharField(blank=True, choices=[('Public', 'Public'), ('Private', 'Private')], default='Private', max_length=30, null=True, verbose_name='Usage Permission')),
                ('public_license', models.CharField(blank=True, max_length=30, null=True, verbose_name='Public License')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='glossary_project', to='ai_workspace.project')),
            ],
        ),
        migrations.CreateModel(
            name='GlossaryFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=1000, upload_to=ai_glex.models.get_file_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx'])])),
                ('filename', models.CharField(max_length=200, null=True)),
                ('fid', models.TextField(blank=True, null=True)),
                ('source_only', models.BooleanField(default=False)),
                ('deleted_at', models.BooleanField(default=False)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='ai_workspace.job')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_files', to='ai_workspace.project')),
                ('usage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glossary_project_usage_type', to='ai_staff.assetusagetypes')),
            ],
        ),
        migrations.CreateModel(
            name='TermsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_term', models.CharField(max_length=200)),
                ('tl_term', models.CharField(blank=True, max_length=200, null=True)),
                ('pos', models.CharField(blank=True, max_length=200, null=True)),
                ('sl_definition', models.TextField(blank=True, max_length=1000, null=True)),
                ('tl_definition', models.TextField(blank=True, max_length=1000, null=True)),
                ('context', models.TextField(blank=True, max_length=1000, null=True)),
                ('note', models.TextField(blank=True, max_length=1000, null=True)),
                ('sl_source', models.CharField(blank=True, max_length=200, null=True)),
                ('tl_source', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('termtype', models.CharField(blank=True, max_length=200, null=True)),
                ('geographical_usage', models.CharField(blank=True, max_length=200, null=True)),
                ('usage_status', models.CharField(blank=True, max_length=200, null=True)),
                ('term_location', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term_file', to='ai_glex.glossaryfiles')),
                ('glossary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term', to='ai_glex.glossary')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term_job', to='ai_workspace.job')),
            ],
        ),
        migrations.CreateModel(
            name='Tbx_Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termbase_Name', models.CharField(max_length=20)),
                ('customer', models.TextField()),
                ('project', models.TextField()),
                ('note', models.TextField()),
                ('glossary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_glex.glossary')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyGlossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_term', models.CharField(max_length=200, null=True)),
                ('tl_term', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_glossary_project', to='ai_workspace.project')),
                ('sl_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_glossary_source_language', to='ai_staff.languages')),
                ('tl_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_glossary_target_language', to='ai_staff.languages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_glossary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GlossaryTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glossary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='ai_glex.glossary')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_task', to='ai_workspace.job')),
            ],
        ),
        migrations.CreateModel(
            name='GlossaryMt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('target_mt', models.CharField(blank=True, max_length=200, null=True)),
                ('mt_engine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term_mt_engine', to='ai_staff.ailaysasupportedmtpeengines')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term_task', to='ai_workspace.task')),
            ],
        ),
        migrations.CreateModel(
            name='GlossarySelected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glossary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glossary', to='ai_glex.glossary')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='ai_workspace.project')),
            ],
            options={
                'unique_together': {('project', 'glossary')},
            },
        ),
    ]
