# Generated by Django 3.2.12 on 2024-01-23 09:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_glex', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='myglossary',
            unique_together={('sl_term', 'tl_term', 'user')},
        ),
    ]
