# Generated by Django 3.2.12 on 2024-02-29 12:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_glex', '0003_myglossary_created_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='myglossary',
            unique_together={('sl_term', 'user')},
        ),
    ]
