# Generated by Django 3.2.12 on 2024-04-18 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0019_auto_20240111_1221'),
        ('ai_glex', '0004_alter_myglossary_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminologyextract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='pdf_file')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_choice_list_project', to='ai_workspace.project')),
            ],
        ),
    ]
