# Generated by Django 3.2.12 on 2024-07-23 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0019_auto_20240111_1221'),
        ('ai_glex', '0005_terminologyextract'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossary',
            name='file_translate_glossary',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_gloss_project', to='ai_workspace.project'),
        ),
    ]
