# Generated by Django 3.2.12 on 2024-07-30 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0020_file_done_extraction'),
        ('ai_glex', '0006_glossary_file_translate_glossary'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryStatusForTermExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200, null=True)),
                ('celery_id', models.CharField(max_length=200, null=True)),
                ('done_extraction', models.BooleanField(default=False)),
                ('gloss_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term_job_default_glossary', to='ai_workspace.job')),
                ('gloss_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='termsmodel_default_glossary', to='ai_glex.glossary')),
                ('term_model_file', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='termsmodel_file_default_glossary', to='ai_workspace.file')),
            ],
        ),
    ]
