# Generated by Django 3.2.12 on 2024-07-31 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_glex', '0007_celerystatusfortermextraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celerystatusfortermextraction',
            name='done_extraction',
        ),
    ]
