# Generated by Django 3.2.12 on 2024-07-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_glex', '0008_remove_celerystatusfortermextraction_done_extraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='celerystatusfortermextraction',
            name='done_extraction',
            field=models.BooleanField(default=False),
        ),
    ]
