# Generated by Django 3.2.12 on 2024-07-31 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_glex', '0009_celerystatusfortermextraction_done_extraction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CeleryStatusForTermExtraction',
        ),
    ]
