# Generated by Django 3.2.12 on 2024-07-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_glex', '0010_delete_celerystatusfortermextraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossary',
            name='is_default_project_glossary',
            field=models.BooleanField(default=False),
        ),
    ]
