# Generated by Django 3.2.12 on 2024-08-01 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0022_file_is_extract'),
        ('ai_glex', '0011_glossary_is_default_project_glossary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossary',
            name='file_translate_glossary',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_gloss_project', to='ai_workspace.project'),
        ),
    ]
