# Generated by Django 3.2.12 on 2024-08-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_glex', '0012_alter_glossary_file_translate_glossary'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossaryfiles',
            name='celery_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='glossaryfiles',
            name='done_extraction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='glossaryfiles',
            name='is_extract',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='glossaryfiles',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
