# Generated by Django 3.2.12 on 2024-08-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_glex', '0015_alter_glossary_file_translate_glossary'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsmodel',
            name='sl_term_translate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
