# Generated by Django 3.2.12 on 2024-09-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_glex', '0016_termsmodel_sl_term_translate'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsmodel',
            name='root_word',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
