# Generated by Django 3.2.12 on 2022-08-17 14:55

import ai_marketplace.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('ai_marketplace', '0001_initial'), ('ai_marketplace', '0002_initial'), ('ai_marketplace', '0003_alter_thread_unique_together'), ('ai_marketplace', '0004_auto_20220616_1403'), ('ai_marketplace', '0005_auto_20220616_1437'), ('ai_marketplace', '0006_auto_20220616_1437'), ('ai_marketplace', '0007_auto_20220629_1247'), ('ai_marketplace', '0008_bidpropasaldetails_is_shortlisted')]

    initial = True

    dependencies = [
        ('ai_workspace', '0010_alter_taskassigninfo_mtpe_rate'),
        ('ai_workspace', '0001_initial'),
        ('ai_staff', '0006_currencybasedoncountry_mtlanguagelocalevoicesupport_mtlanguagesupport_projecttype_projecttypedetail'),
        ('ai_staff', '0001_initial'),
        ('ai_workspace', '0009_auto_20220616_1437'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BidPropasalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_completion_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sample_file_upload', models.FileField(blank=True, null=True, upload_to=ai_marketplace.models.user_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BidStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=191, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectboardDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=191, null=True)),
                ('proj_name', models.CharField(blank=True, max_length=191, null=True)),
                ('proj_desc', models.CharField(blank=True, max_length=5000, null=True)),
                ('bid_deadline', models.DateTimeField(blank=True, null=True)),
                ('proj_deadline', models.DateTimeField(blank=True, null=True)),
                ('ven_special_req', models.CharField(blank=True, max_length=1000, null=True)),
                ('rate_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rate_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('milestone', models.CharField(blank=True, max_length=191, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_currency', to='ai_staff.currencies')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_detail', to='ai_workspace.project')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_unit', to='ai_staff.billingunits')),
                ('ven_native_lang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_native_lang', to='ai_staff.languages')),
                ('ven_res_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res_country', to='ai_staff.countries')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('post_word_count', models.IntegerField(blank=True, null=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_bid', to='ai_marketplace.bidpropasaldetails')),
                ('first_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_first_person', to=settings.AUTH_USER_MODEL)),
                ('second_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_second_person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('first_person', 'second_person')},
            },
        ),
        migrations.CreateModel(
            name='ProjectPostSubjectField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectpost_subject', to='ai_marketplace.projectboarddetails')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectpost_subject', to='ai_staff.subjectfields')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPostJobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectpost_jobs', to='ai_marketplace.projectboarddetails')),
                ('src_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectpost_source_lang', to='ai_staff.languages')),
                ('tar_lang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectpost_target_lang', to='ai_staff.languages')),
                ('postjob_id', models.CharField(blank=True, max_length=191, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPostContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectpost_content_type', to='ai_staff.contenttypes')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectpost_content_type', to='ai_marketplace.projectboarddetails')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatmessage_thread', to='ai_marketplace.thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bidpropasaldetails',
            name='projectpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidproject_details', to='ai_marketplace.projectboarddetails'),
        ),
        migrations.AddField(
            model_name='bidpropasaldetails',
            name='projectpostjob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidjob_details', to='ai_marketplace.projectpostjobdetails'),
        ),
        migrations.AddField(
            model_name='bidpropasaldetails',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_sent_vendor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BidChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('projectpost_jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidding_job', to='ai_marketplace.projectpostjobdetails')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='AvailableJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectpost', to='ai_marketplace.projectboarddetails')),
                ('projectpostjob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projpostjob_details', to='ai_marketplace.projectpostjobdetails')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='bidpropasaldetails',
            unique_together={('projectpostjob', 'vendor')},
        ),
        migrations.CreateModel(
            name='ProjectboardTemplateDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=1000)),
                ('service', models.CharField(blank=True, max_length=191, null=True)),
                ('proj_name', models.CharField(blank=True, max_length=191, null=True)),
                ('proj_desc', models.CharField(blank=True, max_length=5000, null=True)),
                ('bid_deadline', models.DateTimeField(blank=True, null=True)),
                ('proj_deadline', models.DateTimeField(blank=True, null=True)),
                ('ven_special_req', models.CharField(blank=True, max_length=1000, null=True)),
                ('rate_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rate_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('milestone', models.CharField(blank=True, max_length=191, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ven_currency_detail', to='ai_staff.currencies')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_detail', to='ai_workspace.project')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_unit', to='ai_staff.billingunits')),
                ('ven_native_lang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ven_native_lang', to='ai_staff.languages')),
                ('ven_res_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ven_country', to='ai_staff.countries')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPostSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projectpost_steps', to='ai_marketplace.projectboarddetails')),
                ('steps', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projectpost_steps', to='ai_workspace.steps')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPostTemplateContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projectposttemp_content_type', to='ai_staff.contenttypes')),
                ('projectpost_template', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projectposttemp_content_type', to='ai_marketplace.projectboardtemplatedetails')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPostTemplateJobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectpost_template', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projectposttemp_jobs', to='ai_marketplace.projectboardtemplatedetails')),
                ('src_lang', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projectposttemp_source_lang', to='ai_staff.languages')),
                ('tar_lang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectposttemp_target_lang', to='ai_staff.languages')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPostTemplateSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectpost_template', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projectposttemp_steps', to='ai_marketplace.projectboardtemplatedetails')),
                ('steps', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projectposttemp_steps', to='ai_workspace.steps')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPostTemplateSubjectField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectpost_template', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projectposttemp_subject', to='ai_marketplace.projectboardtemplatedetails')),
                ('subject', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projectposttemp_subject', to='ai_staff.subjectfields')),
            ],
        ),
        migrations.RenameField(
            model_name='bidpropasaldetails',
            old_name='sample_file_upload',
            new_name='sample_file',
        ),
        migrations.AddField(
            model_name='bidpropasaldetails',
            name='bid_step',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidpost_steps', to='ai_workspace.steps'),
        ),
        migrations.AddField(
            model_name='bidpropasaldetails',
            name='bidpostjob',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bid_details', to='ai_marketplace.projectpostjobdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bidpropasaldetails',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidding_currency_detail', to='ai_staff.currencies'),
        ),
        migrations.AddField(
            model_name='bidpropasaldetails',
            name='edited_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidpropasaldetails',
            name='mtpe_count_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_job_mtpe_unit_type', to='ai_staff.servicetypeunits'),
        ),
        migrations.AddField(
            model_name='bidpropasaldetails',
            name='mtpe_hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bidpropasaldetails',
            name='mtpe_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bidpropasaldetails',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_status', to='ai_marketplace.bidstatus'),
        ),
        migrations.AlterField(
            model_name='bidpropasaldetails',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_proposal_vendor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='bidpropasaldetails',
            unique_together={('bidpostjob', 'vendor', 'bid_step')},
        ),
        migrations.RemoveField(
            model_name='bidpropasaldetails',
            name='projectpostjob',
        ),
        migrations.AddField(
            model_name='bidpropasaldetails',
            name='is_shortlisted',
            field=models.BooleanField(default=False),
        ),
    ]
