# Generated by Django 3.2.4 on 2021-09-27 08:08

import ai_marketplace.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableVendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BidChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='BidPropasalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_completion_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sample_file_upload', models.FileField(blank=True, null=True, upload_to=ai_marketplace.models.user_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BidProposalServicesRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtpe_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mtpe_hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BidStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=191, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectboardDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=191, null=True)),
                ('steps', models.CharField(blank=True, max_length=191, null=True)),
                ('proj_name', models.CharField(blank=True, max_length=191, null=True)),
                ('proj_desc', models.CharField(blank=True, max_length=1000, null=True)),
                ('bid_deadline', models.DateTimeField(blank=True, null=True)),
                ('proj_deadline', models.DateTimeField(blank=True, null=True)),
                ('ven_special_req', models.CharField(blank=True, max_length=1000, null=True)),
                ('cust_pc_name', models.CharField(blank=True, max_length=191, null=True)),
                ('cust_pc_email', models.CharField(blank=True, max_length=191, null=True)),
                ('rate_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rate_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('milestone', models.CharField(blank=True, max_length=191, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ven_currency', to='ai_staff.currencies')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_bid', to='ai_marketplace.bidpropasaldetails')),
                ('first_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_first_person', to=settings.AUTH_USER_MODEL)),
                ('second_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_second_person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPostSubjectField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectpost_subject', to='ai_marketplace.projectboarddetails')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectpost_subject', to='ai_staff.subjectfields')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPostJobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectpost_jobs', to='ai_marketplace.projectboarddetails')),
                ('src_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectpost_source_lang', to='ai_staff.languages')),
                ('tar_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectpost_target_lang', to='ai_staff.languages')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPostContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectpost_content_type', to='ai_staff.contenttypes')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectpost_content_type', to='ai_marketplace.projectboarddetails')),
            ],
        ),
    ]
