# Generated by Django 3.2.12 on 2022-08-18 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0002_workspace02'),
        ('ai_staff', '0002_auto_20220818_0703'),
        ('ai_marketplace', '0001_marketplace01'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpoststeps',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectpost_steps', to='ai_marketplace.projectboarddetails'),
        ),
        migrations.AlterField(
            model_name='projectpoststeps',
            name='steps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectpost_steps', to='ai_workspace.steps'),
        ),
        migrations.AlterField(
            model_name='projectposttemplatecontenttype',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectposttemp_content_type', to='ai_staff.contenttypes'),
        ),
        migrations.AlterField(
            model_name='projectposttemplatecontenttype',
            name='projectpost_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectposttemp_content_type', to='ai_marketplace.projectboardtemplatedetails'),
        ),
        migrations.AlterField(
            model_name='projectposttemplatejobdetails',
            name='projectpost_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectposttemp_jobs', to='ai_marketplace.projectboardtemplatedetails'),
        ),
        migrations.AlterField(
            model_name='projectposttemplatejobdetails',
            name='src_lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectposttemp_source_lang', to='ai_staff.languages'),
        ),
        migrations.AlterField(
            model_name='projectposttemplatesteps',
            name='projectpost_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectposttemp_steps', to='ai_marketplace.projectboardtemplatedetails'),
        ),
        migrations.AlterField(
            model_name='projectposttemplatesteps',
            name='steps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectposttemp_steps', to='ai_workspace.steps'),
        ),
        migrations.AlterField(
            model_name='projectposttemplatesubjectfield',
            name='projectpost_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectposttemp_subject', to='ai_marketplace.projectboardtemplatedetails'),
        ),
        migrations.AlterField(
            model_name='projectposttemplatesubjectfield',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectposttemp_subject', to='ai_staff.subjectfields'),
        ),
    ]
