# Generated by Django 3.2.4 on 2021-09-27 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_workspace', '0001_initial'),
        ('ai_marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectboarddetails',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_detail', to='ai_workspace.project'),
        ),
        migrations.AddField(
            model_name='projectboarddetails',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_unit', to='ai_staff.billingunits'),
        ),
        migrations.AddField(
            model_name='projectboarddetails',
            name='ven_native_lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_native_lang', to='ai_staff.languages'),
        ),
        migrations.AddField(
            model_name='projectboarddetails',
            name='ven_res_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res_country', to='ai_staff.countries'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatmessage_thread', to='ai_marketplace.thread'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bidproposalservicesrates',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_and_rates', to='ai_marketplace.bidpropasaldetails'),
        ),
        migrations.AddField(
            model_name='bidproposalservicesrates',
            name='mtpe_count_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_job_mtpe_unit_type', to='ai_staff.servicetypeunits'),
        ),
        migrations.AddField(
            model_name='bidpropasaldetails',
            name='projectpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidproject_details', to='ai_marketplace.projectboarddetails'),
        ),
        migrations.AddField(
            model_name='bidpropasaldetails',
            name='projectpostjob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidjob_details', to='ai_marketplace.projectpostjobdetails'),
        ),
        migrations.AddField(
            model_name='bidpropasaldetails',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_status', to='ai_marketplace.bidstatus'),
        ),
        migrations.AddField(
            model_name='bidpropasaldetails',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_sent_vendor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bidchat',
            name='projectpost_jobs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidding_job', to='ai_marketplace.projectpostjobdetails'),
        ),
        migrations.AddField(
            model_name='bidchat',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='availablevendors',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='availablevendors',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='availablejobs',
            name='projectpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectpost', to='ai_marketplace.projectboarddetails'),
        ),
        migrations.AddField(
            model_name='availablejobs',
            name='projectpostjob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projpostjob_details', to='ai_marketplace.projectpostjobdetails'),
        ),
        migrations.AddField(
            model_name='availablejobs',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='thread',
            unique_together={('first_person', 'second_person', 'bid')},
        ),
        migrations.AlterUniqueTogether(
            name='bidpropasaldetails',
            unique_together={('projectpostjob', 'vendor')},
        ),
    ]
