# Generated by Django 3.2.12 on 2022-09-13 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0003_auto_20220909_1147'),
        ('ai_marketplace', '0002_auto_20220818_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidpropasaldetails',
            name='mtpe_count_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_job_mtpe_unit_type', to='ai_staff.billingunits'),
        ),
        migrations.DeleteModel(
            name='AvailableJobs',
        ),
    ]
