# Generated by Django 3.2.4 on 2022-06-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_marketplace', '0003_alter_thread_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectboardTemplateDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=1000)),
                ('service', models.CharField(blank=True, max_length=191, null=True)),
                ('proj_name', models.CharField(blank=True, max_length=191, null=True)),
                ('proj_desc', models.CharField(blank=True, max_length=5000, null=True)),
                ('bid_deadline', models.DateTimeField(blank=True, null=True)),
                ('proj_deadline', models.DateTimeField(blank=True, null=True)),
                ('ven_special_req', models.CharField(blank=True, max_length=1000, null=True)),
                ('rate_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rate_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('milestone', models.CharField(blank=True, max_length=191, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPostSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPostTemplateContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPostTemplateJobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPostTemplateSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPostTemplateSubjectField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='availablevendors',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='availablevendors',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='bidproposalservicesrates',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='bidproposalservicesrates',
            name='mtpe_count_unit',
        ),
        migrations.RenameField(
            model_name='bidpropasaldetails',
            old_name='sample_file_upload',
            new_name='sample_file',
        ),
        migrations.RemoveField(
            model_name='projectboarddetails',
            name='cust_pc_email',
        ),
        migrations.RemoveField(
            model_name='projectboarddetails',
            name='cust_pc_name',
        ),
        migrations.RemoveField(
            model_name='projectboarddetails',
            name='steps',
        ),
    ]
