# Generated by Django 3.2.12 on 2022-11-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_marketplace', '0003_auto_20220913_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidpropasaldetails',
            name='mtpe_hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='bidpropasaldetails',
            name='mtpe_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
