# Generated by Django 3.2.12 on 2023-06-20 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0013_auto_20230620_1045'),
        ('ai_marketplace', '0004_auto_20221111_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectboarddetails',
            name='project_brief',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectboarddetails',
            name='proj_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projectboarddetails',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proj_detail', to='ai_workspace.project'),
        ),
        migrations.AlterField(
            model_name='projectboardtemplatedetails',
            name='proj_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
