# Generated by Django 3.2.4 on 2022-06-16 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_marketplace', '0004_auto_20220616_1403'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvailableVendors',
        ),
        migrations.DeleteModel(
            name='BidProposalServicesRates',
        ),
    ]
