# Generated by Django 3.2.12 on 2023-09-30 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_marketplace', '0005_auto_20230620_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProzMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proz_uuid', models.CharField(blank=True, max_length=250, null=True)),
                ('proz_message_id', models.CharField(blank=True, max_length=250, null=True)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('job_notify', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
