# Generated by Django 3.2.4 on 2022-06-16 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_staff', '0006_currencybasedoncountry_mtlanguagelocalevoicesupport_mtlanguagesupport_projecttype_projecttypedetail'),
        ('ai_marketplace', '0005_auto_20220616_1437'),
        ('ai_workspace', '0009_auto_20220616_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidpropasaldetails',
            name='bid_step',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidpost_steps', to='ai_workspace.steps'),
        ),
        migrations.AddField(
            model_name='bidpropasaldetails',
            name='bidpostjob',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bid_details', to='ai_marketplace.projectpostjobdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bidpropasaldetails',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidding_currency_detail', to='ai_staff.currencies'),
        ),
        migrations.AddField(
            model_name='bidpropasaldetails',
            name='edited_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidpropasaldetails',
            name='mtpe_count_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_job_mtpe_unit_type', to='ai_staff.servicetypeunits'),
        ),
        migrations.AddField(
            model_name='bidpropasaldetails',
            name='mtpe_hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bidpropasaldetails',
            name='mtpe_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='projectboarddetails',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectboarddetails',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectboarddetails',
            name='post_word_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectboardtemplatedetails',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ven_currency_detail', to='ai_staff.currencies'),
        ),
        migrations.AddField(
            model_name='projectboardtemplatedetails',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectboardtemplatedetails',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_detail', to='ai_workspace.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectboardtemplatedetails',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_unit', to='ai_staff.billingunits'),
        ),
        migrations.AddField(
            model_name='projectboardtemplatedetails',
            name='ven_native_lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ven_native_lang', to='ai_staff.languages'),
        ),
        migrations.AddField(
            model_name='projectboardtemplatedetails',
            name='ven_res_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ven_country', to='ai_staff.countries'),
        ),
        migrations.AddField(
            model_name='projectpostjobdetails',
            name='postjob_id',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='projectpoststeps',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projectpost_steps', to='ai_marketplace.projectboarddetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectpoststeps',
            name='steps',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projectpost_steps', to='ai_workspace.steps'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectposttemplatecontenttype',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projectposttemp_content_type', to='ai_staff.contenttypes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectposttemplatecontenttype',
            name='projectpost_template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projectposttemp_content_type', to='ai_marketplace.projectboardtemplatedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectposttemplatejobdetails',
            name='projectpost_template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projectposttemp_jobs', to='ai_marketplace.projectboardtemplatedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectposttemplatejobdetails',
            name='src_lang',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projectposttemp_source_lang', to='ai_staff.languages'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectposttemplatejobdetails',
            name='tar_lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectposttemp_target_lang', to='ai_staff.languages'),
        ),
        migrations.AddField(
            model_name='projectposttemplatesteps',
            name='projectpost_template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projectposttemp_steps', to='ai_marketplace.projectboardtemplatedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectposttemplatesteps',
            name='steps',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projectposttemp_steps', to='ai_workspace.steps'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectposttemplatesubjectfield',
            name='projectpost_template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projectposttemp_subject', to='ai_marketplace.projectboardtemplatedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectposttemplatesubjectfield',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projectposttemp_subject', to='ai_staff.subjectfields'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bidpropasaldetails',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_status', to='ai_marketplace.bidstatus'),
        ),
        migrations.AlterField(
            model_name='bidpropasaldetails',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_proposal_vendor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectboarddetails',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_currency', to='ai_staff.currencies'),
        ),
        migrations.AlterField(
            model_name='projectboarddetails',
            name='proj_desc',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='projectpostjobdetails',
            name='tar_lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectpost_target_lang', to='ai_staff.languages'),
        ),
        migrations.AlterUniqueTogether(
            name='bidpropasaldetails',
            unique_together={('bidpostjob', 'vendor', 'bid_step')},
        ),
        migrations.RemoveField(
            model_name='bidpropasaldetails',
            name='projectpostjob',
        ),
    ]
