# Generated by Django 3.2.4 on 2022-06-29 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0010_alter_taskassigninfo_mtpe_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_marketplace', '0006_auto_20220616_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectboarddetails',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectboardtemplatedetails',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_detail', to='ai_workspace.project'),
        ),
    ]
