# Generated by Django 3.2.4 on 2022-07-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_marketplace', '0007_auto_20220629_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidpropasaldetails',
            name='is_shortlisted',
            field=models.BooleanField(default=False),
        ),
    ]
