# Generated by Django 3.2.4 on 2021-09-27 08:08

import ai_workspace.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='/ai_home/media/defualt.zip', max_length=1000, upload_to=ai_workspace.models.get_file_upload_path)),
                ('filename', models.CharField(max_length=200, null=True)),
                ('fid', models.TextField(blank=True, null=True)),
                ('deleted_at', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FileTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type_name', models.CharField(choices=[('source', 'Src'), ('reference', 'Ref'), ('translation_memory', 'TM'), ('blockedtext', 'qa_BT'), ('untranslatable', 'qa_UT'), ('termbase', 'TB')], max_length=100)),
                ('file_type_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.TextField(blank=True, null=True)),
                ('deleted_at', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PenseiveTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penseive_tm_dir_path', models.FilePathField(allow_files=False, allow_folders=True, blank=True, max_length=1000, null=True, path='/ai_home/media')),
                ('source_tmx_dir_path', models.FilePathField(allow_files=False, allow_folders=True, blank=True, max_length=1000, null=True, path='/ai_home/media')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('project_name', models.CharField(blank=True, max_length=50, null=True)),
                ('project_dir_path', models.FilePathField(allow_files=False, allow_folders=True, blank=True, max_length=1000, null=True, path='/ai_home/media')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('ai_project_id', models.TextField()),
                ('threshold', models.IntegerField(default=85)),
                ('max_hits', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSubjectField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_files', models.FileField(upload_to=ai_workspace.models.reference_file_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TbxTemplateFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tbx_template_file', models.FileField(upload_to=ai_workspace.models.tbx_template_file_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx'])])),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_workspace.job')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_workspace.project')),
            ],
        ),
        migrations.CreateModel(
            name='TempProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_proj_id', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(choices=[('POST_EDITING', 'post_editing')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TmxFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmx_file', models.FileField(upload_to=ai_workspace.models.TmxFile.tmx_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['tmx'])])),
                ('is_processed', models.BooleanField(default=False)),
                ('is_failed', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tmx_files', to='ai_workspace.project')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateTermsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_term', models.CharField(blank=True, max_length=200, null=True)),
                ('tl_term', models.CharField(blank=True, max_length=200, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_workspace.tbxtemplatefiles')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_workspace.job')),
            ],
        ),
        migrations.CreateModel(
            name='Templangpair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_proj_langpair', to='ai_workspace.tempproject')),
                ('temp_src_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_source_lang', to='ai_staff.languages')),
                ('temp_tar_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_target_lang', to='ai_staff.languages')),
            ],
        ),
        migrations.CreateModel(
            name='TempFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files_temp', models.FileField(max_length=1000, upload_to=ai_workspace.models.get_temp_file_upload_path)),
                ('temp_proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_proj_file', to='ai_workspace.tempproject')),
            ],
        ),
        migrations.CreateModel(
            name='Tbxfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tbx_files', models.FileField(max_length=1000, upload_to='uploaded_tbx_files')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_workspace.project')),
            ],
        ),
        migrations.CreateModel(
            name='TbxFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tbx_file', models.FileField(upload_to=ai_workspace.models.tbx_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['tbx'])])),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_tbx_file', to='ai_workspace.job')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tbx_file', to='ai_workspace.project')),
            ],
        ),
        migrations.CreateModel(
            name='TaskCreditStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_credits', models.IntegerField()),
                ('actual_used_credits', models.IntegerField()),
                ('word_char_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_workspace.task')),
            ],
        ),
    ]
