# Generated by Django 3.2.4 on 2021-09-27 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_staff', '0001_initial'),
        ('ai_workspace_okapi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_workspace_okapi.document'),
        ),
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_tasks_set', to='ai_workspace.file'),
        ),
        migrations.AddField(
            model_name='task',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_tasks_set', to='ai_workspace.job'),
        ),
        migrations.AddField(
            model_name='task',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_tasks_set', to='ai_workspace.version'),
        ),
        migrations.AddField(
            model_name='referencefiles',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_ref_files_set', to='ai_workspace.project'),
        ),
        migrations.AddField(
            model_name='projectsubjectfield',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_subject', to='ai_workspace.project'),
        ),
        migrations.AddField(
            model_name='projectsubjectfield',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_sub_name', to='ai_staff.subjectfields'),
        ),
        migrations.AddField(
            model_name='projectcontenttype',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_content_type_name', to='ai_staff.contenttypes'),
        ),
        migrations.AddField(
            model_name='projectcontenttype',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_content_type', to='ai_workspace.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='ai_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='mt_engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proj_mt_engine', to='ai_staff.ailaysasupportedmtpeengines'),
        ),
        migrations.AddField(
            model_name='penseivetm',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_penseivetm', to='ai_workspace.project'),
        ),
        migrations.AddField(
            model_name='job',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_jobs_set', to='ai_workspace.project'),
        ),
        migrations.AddField(
            model_name='job',
            name='source_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_language', to='ai_staff.languages'),
        ),
        migrations.AddField(
            model_name='job',
            name='target_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_language', to='ai_staff.languages'),
        ),
        migrations.AddField(
            model_name='file',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_files_set', to='ai_workspace.project'),
        ),
        migrations.AddField(
            model_name='file',
            name='usage_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_usage_type', to='ai_staff.assetusagetypes'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('file', 'job', 'version'), name='file, job, version combination unique'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('project_name', 'ai_user')},
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('project', 'source_language', 'target_language')},
        ),
    ]
