# Generated by Django 3.2.12 on 2022-08-17 15:02

import ai_workspace.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('ai_workspace', '0002_initial'), ('ai_workspace', '0003_auto_20211007_1026'), ('ai_workspace', '0004_remove_project_deleted_at'), ('ai_workspace', '0005_taskdetails'), ('ai_workspace', '0006_auto_20220120_1322'), ('ai_workspace', '0007_alter_file_options'), ('ai_workspace', '0008_alter_project_project_name'), ('ai_workspace', '0009_auto_20220616_1437'), ('ai_workspace', '0010_alter_taskassigninfo_mtpe_rate'), ('ai_workspace', '0011_auto_20220707_0533'), ('ai_workspace', '0012_auto_20220811_1144')]

    dependencies = [
        ('ai_staff', '0006_currencybasedoncountry_mtlanguagelocalevoicesupport_mtlanguagesupport_projecttype_projecttypedetail'),
        ('ai_staff', '0001_initial'),
        ('ai_staff', '0004_role'),
        ('ai_workspace_okapi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_workspace', '0001_initial'),
        ('ai_auth', '0016_auto_20220120_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_workspace_okapi.document'),
        ),
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_tasks_set', to='ai_workspace.file'),
        ),
        migrations.AddField(
            model_name='task',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_tasks_set', to='ai_workspace.job'),
        ),
        migrations.AddField(
            model_name='task',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_tasks_set', to='ai_workspace.version'),
        ),
        migrations.AddField(
            model_name='referencefiles',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_ref_files_set', to='ai_workspace.project'),
        ),
        migrations.AddField(
            model_name='projectsubjectfield',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_subject', to='ai_workspace.project'),
        ),
        migrations.AddField(
            model_name='projectsubjectfield',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_sub_name', to='ai_staff.subjectfields'),
        ),
        migrations.AddField(
            model_name='projectcontenttype',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_content_type_name', to='ai_staff.contenttypes'),
        ),
        migrations.AddField(
            model_name='projectcontenttype',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_content_type', to='ai_workspace.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='ai_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='mt_engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proj_mt_engine', to='ai_staff.ailaysasupportedmtpeengines'),
        ),
        migrations.AddField(
            model_name='penseivetm',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_penseivetm', to='ai_workspace.project'),
        ),
        migrations.AddField(
            model_name='job',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_jobs_set', to='ai_workspace.project'),
        ),
        migrations.AddField(
            model_name='job',
            name='source_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_language', to='ai_staff.languages'),
        ),
        migrations.AddField(
            model_name='job',
            name='target_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_language', to='ai_staff.languages'),
        ),
        migrations.AddField(
            model_name='file',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_files_set', to='ai_workspace.project'),
        ),
        migrations.AddField(
            model_name='file',
            name='usage_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_usage_type', to='ai_staff.assetusagetypes'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('file', 'job', 'version'), name='file, job, version combination unique'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('project_name', 'ai_user')},
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('project', 'source_language', 'target_language')},
        ),
        migrations.RenameField(
            model_name='tempfiles',
            old_name='files_temp',
            new_name='files',
        ),
        migrations.RenameField(
            model_name='templangpair',
            old_name='temp_src_lang',
            new_name='source_language',
        ),
        migrations.RenameField(
            model_name='templangpair',
            old_name='temp_tar_lang',
            new_name='target_language',
        ),
        migrations.RemoveField(
            model_name='project',
            name='deleted_at',
        ),
        migrations.CreateModel(
            name='TaskDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_word_count', models.IntegerField(blank=True, null=True)),
                ('task_char_count', models.IntegerField(blank=True, null=True)),
                ('task_seg_count', models.IntegerField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_project', to='ai_workspace.project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_details', to='ai_workspace.task')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proj_team', to='ai_auth.team'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(default='/ai_home/mediafiles/defualt.zip', max_length=1000, upload_to=ai_workspace.models.get_file_upload_path),
        ),
        migrations.AlterField(
            model_name='penseivetm',
            name='penseive_tm_dir_path',
            field=models.FilePathField(allow_files=False, allow_folders=True, blank=True, max_length=1000, null=True, path='/ai_home/mediafiles'),
        ),
        migrations.AlterField(
            model_name='penseivetm',
            name='source_tmx_dir_path',
            field=models.FilePathField(allow_files=False, allow_folders=True, blank=True, max_length=1000, null=True, path='/ai_home/mediafiles'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_dir_path',
            field=models.FilePathField(allow_files=False, allow_folders=True, blank=True, max_length=1000, null=True, path='/ai_home/mediafiles'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assign_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_tasks_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ai_staff.projecttype'),
        ),
        migrations.AddField(
            model_name='task',
            name='ai_taskid',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tempproject',
            name='mt_engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_proj_mt_engine', to='ai_staff.ailaysasupportedmtpeengines'),
        ),
        migrations.AlterField(
            model_name='job',
            name='target_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_language', to='ai_staff.languages'),
        ),
        migrations.AlterField(
            model_name='project',
            name='mt_engine',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proj_mt_engine', to='ai_staff.ailaysasupportedmtpeengines'),
        ),
        migrations.CreateModel(
            name='VoiceProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_proj_detail', to='ai_workspace.project')),
                ('project_type_sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_staff.projecttypedetail')),
                ('source_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_proj_source_language', to='ai_staff.languages')),
            ],
        ),
        migrations.CreateModel(
            name='TaskTranscriptDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcripted_text', models.TextField(blank=True, null=True)),
                ('source_audio_file', models.FileField(blank=True, null=True, upload_to=ai_workspace.models.audio_file_path)),
                ('translated_audio_file', models.FileField(blank=True, null=True, upload_to=ai_workspace.models.audio_file_path)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_transcript_details', to='ai_workspace.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_segment_confirmed', models.IntegerField(blank=True, null=True)),
                ('previous_assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assign_history', to='ai_workspace.task')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('unassigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unassigned_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField(blank=True, max_length=1000, null=True)),
                ('instruction_file', models.FileField(blank=True, null=True, upload_to=ai_workspace.models.ref_file_upload_path)),
                ('assignment_id', models.CharField(blank=True, max_length=191, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('total_word_count', models.IntegerField(blank=True, null=True)),
                ('mtpe_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_assign_info', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_currency', to='ai_staff.currencies')),
                ('mtpe_count_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_unit', to='ai_staff.billingunits')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_assign_info', to='ai_workspace.task')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[('outside_ailaysa', 'outside_ailaysa'), ('stripe', 'stripe')], max_length=20, null=True)),
                ('task_ven_status', models.CharField(blank=True, choices=[('task_accepted', 'task_accepted'), ('change_request', 'change_request')], max_length=20, null=True)),
            ],
        ),
    ]
