# Generated by Django 3.2.12 on 2022-09-09 11:47

import ai_workspace.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_staff', '0003_auto_20220909_1147'),
        ('ai_workspace', '0002_workspace02'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructionfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_file', models.FileField(blank=True, null=True, upload_to=ai_workspace.models.ref_file_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFilesCreateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_create_type', models.TextField(choices=[('upload', 'Files from usual upload'), ('integeration', 'Files from integerations')], default='upload')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_translate', models.BooleanField(blank=True, null=True)),
                ('mt_enable', models.BooleanField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Yet to start'), (2, 'In Progress'), (3, 'Completed')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Workflows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('standard', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'managed': True},
        ),
        migrations.RemoveConstraint(
            model_name='task',
            name='file, job, version combination unique',
        ),
        migrations.AddField(
            model_name='project',
            name='mt_enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pre_translate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='project_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskassigninfo',
            name='estimated_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasktranscriptdetails',
            name='audio_file_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tasktranscriptdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tasktranscriptdetails',
            name='quill_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasktranscriptdetails',
            name='transcripted_file_writer',
            field=models.FileField(blank=True, null=True, upload_to=ai_workspace.models.edited_file_path),
        ),
        migrations.AddField(
            model_name='tasktranscriptdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tasktranscriptdetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasktranscriptdetails',
            name='writer_filename',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tasktranscriptdetails',
            name='writer_project_updated_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_tasks_set', to='ai_workspace.file'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('file__isnull', False)), fields=('file', 'job'), name='file, job combination unique if file not null'),
        ),
        migrations.AddField(
            model_name='workflowsteps',
            name='steps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step', to='ai_workspace.steps'),
        ),
        migrations.AddField(
            model_name='workflowsteps',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='ai_workspace.workflows'),
        ),
        migrations.AddField(
            model_name='workflows',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_workflow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskassign',
            name='assign_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_tasks_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskassign',
            name='mt_engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_mt_engine', to='ai_staff.ailaysasupportedmtpeengines'),
        ),
        migrations.AddField(
            model_name='taskassign',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_step', to='ai_workspace.steps'),
        ),
        migrations.AddField(
            model_name='taskassign',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_info', to='ai_workspace.task'),
        ),
        migrations.AddField(
            model_name='projectsteps',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_steps', to='ai_workspace.project'),
        ),
        migrations.AddField(
            model_name='projectsteps',
            name='steps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_steps_name', to='ai_workspace.steps'),
        ),
        migrations.AddField(
            model_name='projectfilescreatetype',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_file_create_type', to='ai_workspace.project'),
        ),
        migrations.AddField(
            model_name='instructionfiles',
            name='task_assign_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_assign_instruction_file', to='ai_workspace.taskassigninfo'),
        ),
        migrations.AddField(
            model_name='project',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proj_workflow', to='ai_workspace.workflows'),
        ),
        migrations.AddField(
            model_name='taskassignhistory',
            name='task_assign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_assign_history', to='ai_workspace.taskassign'),
        ),
        migrations.AddField(
            model_name='taskassigninfo',
            name='task_assign',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_assign_info', to='ai_workspace.taskassign'),
        ),
    ]
