# Generated by Django 3.2.4 on 2021-10-07 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempfiles',
            old_name='files_temp',
            new_name='files',
        ),
        migrations.RenameField(
            model_name='templangpair',
            old_name='temp_src_lang',
            new_name='source_language',
        ),
        migrations.RenameField(
            model_name='templangpair',
            old_name='temp_tar_lang',
            new_name='target_language',
        ),
    ]
