# Generated by Django 3.2.4 on 2021-10-21 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0003_auto_20211007_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='deleted_at',
        ),
    ]
