# Generated by Django 3.2.12 on 2022-09-09 11:58

from django.db import migrations
import logging
logger = logging.getLogger("django")
from ai_workspace.models import TaskAssign

def forwards(apps, schema_editor):
    if schema_editor.connection.alias != 'default':
        return
    Task = apps.get_model('ai_workspace', 'Task')
    TaskAssign = apps.get_model('ai_workspace', 'TaskAssign')
    TaskAssignInfo = apps.get_model('ai_workspace', 'TaskAssignInfo')
    TaskAssignHistory = apps.get_model('ai_workspace', 'TaskAssignHistory')
    Instructionfiles = apps.get_model('ai_workspace', 'Instructionfiles')
    
    tasks = Task.objects.all()
    for task in tasks :
        try:
            tsk_info = TaskAssignInfo.objects.get(task=task)
        except TaskAssignInfo.DoesNotExist:
            logger.error(f"task_assign info not found for task :{task.id}")
            tsk_info = None

        mt_engine = task.job.project.mt_engine
        assign_to = task.assign_to
        # task = tsk_info.task


        insert = {'task':task,'step_id':1,'assign_to':assign_to,'mt_engine':mt_engine}
        task_assign=TaskAssign.objects.create(**insert)
        if task_assign == None:
            raise ValueError("task assing creation failed")

        if tsk_info:
            if task_assign:
                tsk_info.task_assign=task_assign
                tsk_info.save()
            else:
                logger.warning(f"failed migration for task_assign: tsk_info {tsk_info.id}")

            info_file = tsk_info.instruction_file
            instruct_file = Instructionfiles.objects.create(instruction_file=info_file,task_assign_info=tsk_info)
            if not instruct_file:
                logger.warning(f"failed migration for task_assign: tsk_info {tsk_info.id}")

        task_assign_history=task.task_assign_history.filter(task=task).update(task_assign=task_assign)
        logger.info(task_assign_history)
    

class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0003_auto_20220909_1147'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
