# Generated by Django 3.2.12 on 2022-09-13 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0004_auto_20220909_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assign_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='version',
        ),
        migrations.RemoveField(
            model_name='taskassignhistory',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskassigninfo',
            name='instruction_file',
        ),
        migrations.RemoveField(
            model_name='taskassigninfo',
            name='task',
        ),
        migrations.AlterField(
            model_name='taskassignhistory',
            name='task_assign',
            field=models.ForeignKey(blank=True, null=True,on_delete=django.db.models.deletion.CASCADE, related_name='task_assign_history', to='ai_workspace.taskassign'),
        ),
        migrations.AlterField(
            model_name='taskassigninfo',
            name='task_assign',
            field=models.OneToOneField(blank=True, null=True,on_delete=django.db.models.deletion.CASCADE, related_name='task_assign_info', to='ai_workspace.taskassign'),
        ),
    ]
