# Generated by Django 3.2.4 on 2021-12-21 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0004_remove_project_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_word_count', models.IntegerField(blank=True, null=True)),
                ('task_char_count', models.IntegerField(blank=True, null=True)),
                ('task_seg_count', models.IntegerField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_project', to='ai_workspace.project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_details', to='ai_workspace.task')),
            ],
        ),
    ]
