# Generated by Django 3.2.12 on 2022-09-28 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0003_auto_20220909_1147'),
        ('ai_workspace', '0005_auto_20220913_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='copy_paste_enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='taskassign',
            name='copy_paste_enable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectfilescreatetype',
            name='file_create_type',
            field=models.TextField(choices=[('upload', 'Files from usual upload'), ('integeration', 'Files from integerations'), ('From insta text', 'From Text')], default='upload'),
        ),
        migrations.AlterField(
            model_name='tasktranscriptdetails',
            name='audio_file_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MTonlytaskCeleryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'In Progress'), (2, 'Completed')], default=1)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mt_only_task_status', to='ai_workspace.task')),
            ],
        ),
        migrations.CreateModel(
            name='ExpressProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_text', models.TextField(blank=True, null=True)),
                ('mt_raw', models.TextField(blank=True, null=True)),
                ('mt_engine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='express_proj_mt_detail', to='ai_staff.ailaysasupportedmtpeengines')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='express_task_detail', to='ai_workspace.task')),
            ],
        ),
    ]
