# Generated by Django 3.2.4 on 2022-01-20 13:22

import ai_workspace.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0004_role'),
        ('ai_auth', '0016_auto_20220120_1322'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_workspace', '0005_taskdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proj_team', to='ai_auth.team'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(default='/ai_home/mediafiles/defualt.zip', max_length=1000, upload_to=ai_workspace.models.get_file_upload_path),
        ),
        migrations.AlterField(
            model_name='penseivetm',
            name='penseive_tm_dir_path',
            field=models.FilePathField(allow_files=False, allow_folders=True, blank=True, max_length=1000, null=True, path='/ai_home/mediafiles'),
        ),
        migrations.AlterField(
            model_name='penseivetm',
            name='source_tmx_dir_path',
            field=models.FilePathField(allow_files=False, allow_folders=True, blank=True, max_length=1000, null=True, path='/ai_home/mediafiles'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_dir_path',
            field=models.FilePathField(allow_files=False, allow_folders=True, blank=True, max_length=1000, null=True, path='/ai_home/mediafiles'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assign_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_tasks_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TaskAssignInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField(blank=True, max_length=1000, null=True)),
                ('instruction_file', models.FileField(blank=True, null=True, upload_to=ai_workspace.models.ref_file_upload_path)),
                ('assignment_id', models.CharField(blank=True, max_length=191, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('total_word_count', models.IntegerField(blank=True, null=True)),
                ('mtpe_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_assign_info', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_currency', to='ai_staff.currencies')),
                ('mtpe_count_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_unit', to='ai_staff.servicetypeunits')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_assign_info', to='ai_workspace.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_segment_confirmed', models.IntegerField(blank=True, null=True)),
                ('previous_assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assign_history', to='ai_workspace.task')),
            ],
        ),
    ]
