# Generated by Django 3.2.12 on 2022-09-29 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0006_auto_20220928_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassignhistory',
            name='task_assign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assign_history', to='ai_workspace.taskassign'),
        ),
        migrations.AlterField(
            model_name='taskassigninfo',
            name='task_assign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_assign_info', to='ai_workspace.taskassign'),
        ),
    ]
