# Generated by Django 3.2.4 on 2022-03-03 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0006_auto_20220120_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'managed': False},
        ),
    ]
