# Generated by Django 3.2.12 on 2022-10-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0007_auto_20220929_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtonlytaskcelerystatus',
            name='error_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mtonlytaskcelerystatus',
            name='task_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
