# Generated by Django 3.2.12 on 2022-12-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0008_auto_20221019_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassigninfo',
            name='account_raw_count',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='taskassigninfo',
            name='billable_char_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskassigninfo',
            name='billable_word_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
