# Generated by Django 3.2.4 on 2022-06-16 14:37

import ai_workspace.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0006_currencybasedoncountry_mtlanguagelocalevoicesupport_mtlanguagesupport_projecttype_projecttypedetail'),
        ('ai_workspace', '0008_alter_project_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ai_staff.projecttype'),
        ),
        migrations.AddField(
            model_name='task',
            name='ai_taskid',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='taskassigninfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='taskassigninfo',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('outside_ailaysa', 'outside_ailaysa'), ('stripe', 'stripe')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='taskassigninfo',
            name='task_ven_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tempproject',
            name='mt_engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_proj_mt_engine', to='ai_staff.ailaysasupportedmtpeengines'),
        ),
        migrations.AlterField(
            model_name='job',
            name='target_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_language', to='ai_staff.languages'),
        ),
        migrations.AlterField(
            model_name='project',
            name='mt_engine',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proj_mt_engine', to='ai_staff.ailaysasupportedmtpeengines'),
        ),
        migrations.CreateModel(
            name='VoiceProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_proj_detail', to='ai_workspace.project')),
                ('project_type_sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_staff.projecttypedetail')),
                ('source_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_proj_source_language', to='ai_staff.languages')),
            ],
        ),
        migrations.CreateModel(
            name='TaskTranscriptDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcripted_text', models.TextField(blank=True, null=True)),
                ('source_audio_file', models.FileField(blank=True, null=True, upload_to=ai_workspace.models.audio_file_path)),
                ('translated_audio_file', models.FileField(blank=True, null=True, upload_to=ai_workspace.models.audio_file_path)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_transcript_details', to='ai_workspace.task')),
            ],
        ),
    ]
