# Generated by Django 3.2.12 on 2023-02-24 06:22

import ai_workspace.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0006_auto_20230224_0622'),
        ('ai_exportpdf', '0002_auto_20230224_0622'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_workspace', '0009_auto_20221214_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressprojectdetail',
            name='source_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasktranscriptdetails',
            name='html_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='WriterProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('ai_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=ai_workspace.models.my_docs_upload_path)),
                ('doc_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('word_count', models.IntegerField(blank=True, null=True)),
                ('html_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('ai_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_debit_user', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_created_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_docs', to='ai_workspace.writerproject')),
                ('source_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_source_lang', to='ai_staff.languages')),
            ],
        ),
        migrations.CreateModel(
            name='ExpressProjectSrcSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_text_unit', models.IntegerField()),
                ('src_segment', models.TextField(blank=True, null=True)),
                ('seq_id', models.IntegerField()),
                ('version', models.IntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='express_src_text_unit', to='ai_workspace.task')),
            ],
        ),
        migrations.CreateModel(
            name='ExpressProjectSrcMTRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt_raw', models.TextField(blank=True, null=True)),
                ('mt_engine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='express_proj_mt_raw', to='ai_staff.ailaysasupportedmtpeengines')),
                ('src_seg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='express_src_mt', to='ai_workspace.expressprojectsrcsegment')),
            ],
        ),
        migrations.CreateModel(
            name='ExpressProjectAIMT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(blank=True, null=True)),
                ('api_result', models.TextField(blank=True, null=True)),
                ('final_result', models.TextField(blank=True, null=True)),
                ('customize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insta_cust', to='ai_staff.aicustomize')),
                ('express', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='express_src_text', to='ai_workspace.expressprojectdetail')),
                ('mt_engine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='express_proj_mt', to='ai_staff.ailaysasupportedmtpeengines')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to=ai_workspace.models.my_doc_image_upload_path)),
                ('ai_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_image', to='ai_workspace.mydocuments')),
                ('pdf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retd_img', to='ai_exportpdf.ai_pdfupload')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_img', to='ai_workspace.task')),
            ],
        ),
        migrations.CreateModel(
            name='AiRoleandStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_role', to='ai_staff.airoles')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_role', to='ai_workspace.steps')),
            ],
        ),
    ]
