# Generated by Django 3.2.4 on 2022-07-07 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_workspace', '0010_alter_taskassigninfo_mtpe_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='taskassignhistory',
            name='unassigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unassigned_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
