# Generated by Django 3.2.12 on 2023-03-13 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0010_auto_20230224_0622'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressTaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField(blank=True, null=True)),
                ('target_text', models.TextField(blank=True, null=True)),
                ('action', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='express_task_history', to='ai_workspace.task')),
            ],
        ),
    ]
