# Generated by Django 3.2.12 on 2023-05-02 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0007_documenttype'),
        ('ai_workspace', '0011_expresstaskhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtonlytaskcelerystatus',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mt_only_project_status', to='ai_workspace.project'),
        ),
        migrations.AddField(
            model_name='mydocuments',
            name='blog_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mydocuments',
            name='document_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ai_staff.documenttype'),
        ),
    ]
