# Generated by Django 3.2.4 on 2022-08-11 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0006_currencybasedoncountry_mtlanguagelocalevoicesupport_mtlanguagesupport_projecttype_projecttypedetail'),
        ('ai_workspace', '0011_auto_20220707_0533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskassigninfo',
            name='task_ven_accepted',
        ),
        migrations.AddField(
            model_name='taskassigninfo',
            name='task_ven_status',
            field=models.CharField(blank=True, choices=[('task_accepted', 'task_accepted'), ('change_request', 'change_request')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='taskassigninfo',
            name='mtpe_count_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_unit', to='ai_staff.billingunits'),
        ),
    ]
