# Generated by Django 3.2.12 on 2023-06-20 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_workspace', '0012_auto_20230502_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassign',
            name='client_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskassign',
            name='client_response',
            field=models.IntegerField(blank=True, choices=[(1, 'Approved'), (2, 'Rework'), (3, 'Close')], null=True),
        ),
        migrations.AddField(
            model_name='taskassign',
            name='reassigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskassign',
            name='return_request_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskassign',
            name='user_who_approved_or_rejected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskassigninfo',
            name='change_request_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskassign',
            name='status',
            field=models.IntegerField(choices=[(1, 'Yet to start'), (2, 'In Progress'), (3, 'Completed'), (4, 'Return Request')], default=1),
        ),
    ]
