# Generated by Django 3.2.12 on 2023-09-30 17:25

import ai_workspace.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0009_designerorientation_designshape_designshapecategory_fontcatagorylist_fontdata_fontfamily_fontlanguag'),
        ('ai_workspace', '0013_auto_20230620_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='file_translate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='get_mt_by_page',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='TaskTranslatedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_file', models.FileField(blank=True, null=True, upload_to=ai_workspace.models.target_file_upload_path)),
                ('mt_engine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_trans_mt', to='ai_staff.ailaysasupportedmtpeengines')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_file_detail', to='ai_workspace.task')),
            ],
        ),
    ]
