# Generated by Django 3.2.12 on 2023-10-12 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_openai', '0006_auto_20231012_1436'),
        ('ai_workspace', '0014_auto_20230930_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentimages',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_img', to='ai_openai.bookcreation'),
        ),
    ]
