# Generated by Django 3.2.12 on 2023-11-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0015_documentimages_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassigninfo',
            name='deadline_extend_msg_sent',
            field=models.BooleanField(default=False),
        ),
    ]
