# Generated by Django 3.2.12 on 2023-11-24 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0010_auto_20231012_1436'),
        ('ai_workspace', '0016_taskassigninfo_deadline_extend_msg_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskNewsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.CharField(blank=True, max_length=250, null=True)),
                ('source_json', models.JSONField(blank=True, null=True)),
                ('target_json', models.JSONField(blank=True, null=True)),
                ('pushed', models.BooleanField(default=False)),
                ('feed_id', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_task', to='ai_workspace.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskNewsMT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt_raw_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('mt_engine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_news_mt', to='ai_staff.ailaysasupportedmtpeengines')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasknews', to='ai_workspace.tasknewsdetails')),
            ],
        ),
    ]
