# Generated by Django 3.2.12 on 2023-12-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0017_tasknewsdetails_tasknewsmt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfilescreatetype',
            name='file_create_type',
            field=models.TextField(choices=[('upload', 'Files from usual upload'), ('integeration', 'Files from integerations'), ('From insta text', 'From Text'), ('From CMS', 'From Cms'), ('From add story', 'From Stories')], default='upload'),
        ),
    ]
