# Generated by Django 3.2.12 on 2024-01-11 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0018_alter_projectfilescreatetype_file_create_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='taskassign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='TaskAssignStatusChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('new_status', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('task_assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assign_status_history', to='ai_workspace.taskassign')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
