# Generated by Django 3.2.12 on 2024-07-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0019_auto_20240111_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='done_extraction',
            field=models.BooleanField(default=False),
        ),
    ]
