# Generated by Django 3.2.12 on 2024-06-07 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0016_auto_20240516_0644'),
        ('ai_workspace', '0019_auto_20240111_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ai_staff.projecttype'),
        ),
    ]
