# Generated by Django 3.2.12 on 2024-07-31 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0020_file_done_extraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='celery_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='gloss_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term_job_default_glossary', to='ai_workspace.job'),
        ),
        migrations.AddField(
            model_name='file',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
