# Generated by Django 3.2.12 on 2024-07-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0021_auto_20240731_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_extract',
            field=models.BooleanField(default=False),
        ),
    ]
