# Generated by Django 3.2.12 on 2024-08-13 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0022_file_is_extract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='gloss_job',
        ),
    ]
