# Generated by Django 3.2.12 on 2024-08-14 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0023_remove_file_gloss_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTermExtracted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_extraction', to='ai_workspace.file')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_file_extract', to='ai_workspace.task')),
            ],
            options={
                'unique_together': {('task', 'file')},
            },
        ),
    ]
