# Generated by Django 3.2.12 on 2024-08-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0024_filetermextracted'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetermextracted',
            name='celery_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='filetermextracted',
            name='done_extraction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filetermextracted',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
