# Generated by Django 3.2.12 on 2024-10-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0025_auto_20240814_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='isAdaptiveTranslation',
            field=models.BooleanField(default=False),
        ),
    ]
