# Generated by Django 3.2.12 on 2025-03-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0026_project_isadaptivetranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='adaptive_file_translate',
            field=models.BooleanField(default=False),
        ),
    ]
