# Generated by Django 3.2.12 on 2025-03-25 10:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0010_remove_duplicate_indices'),
        ('ai_workspace_okapi', '0024_segmentdiff_target_tags'),
        ('ai_workspace', '0027_project_adaptive_file_translate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackSegmentsBatchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('seg_start_id', models.IntegerField()),
                ('seg_end_id', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_batch_segment_status', to='ai_workspace_okapi.document')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_workspace.project')),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='track_batch_segment_status', to='django_celery_results.taskresult')),
            ],
        ),
    ]
