# Generated by Django 3.2.12 on 2025-03-25 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0028_tracksegmentsbatchstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracksegmentsbatchstatus',
            name='status',
        ),
    ]
