# Generated by Django 3.2.12 on 2025-03-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0032_auto_20250327_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='adaptive_file_translate_status',
            field=models.CharField(choices=[('NOT_INITIATED', 'Translate Not Initiated'), ('ONGOING', 'Translation Ongoing'), ('COMPLETED', 'Translation Completed'), ('FAILED', 'Translation Failed')], default='NOT_INITIATED', max_length=20),
        ),
    ]
