# Generated by Django 3.2.12 on 2025-03-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0033_task_adaptive_file_translate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracksegmentsbatchstatus',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
