# Generated by Django 3.2.12 on 2025-04-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0034_tracksegmentsbatchstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracksegmentsbatchstatus',
            name='error_type',
            field=models.CharField(blank=True, choices=[('INSUFFICIENT_CREDIT', 'INSUFFICIENT_CREDIT'), ('OTHER', 'OTHER')], default=None, max_length=30, null=True),
        ),
    ]
