# Generated by Django 3.2.12 on 2025-04-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0035_tracksegmentsbatchstatus_error_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='adaptive_simple',
            field=models.BooleanField(default=False),
        ),
    ]
