# Generated by Django 3.2.12 on 2025-05-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0037_processfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracksegmentsbatchstatus',
            name='progress_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tracksegmentsbatchstatus',
            name='segment_type',
            field=models.CharField(choices=[('sentence', 'Sentence'), ('paragraph', 'Paragraph')], default='paragraph', max_length=20),
        ),
    ]
