# Generated by Django 3.2.12 on 2025-05-07 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0038_auto_20250502_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStageResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_01', models.TextField(blank=True, null=True)),
                ('stage_02', models.TextField(blank=True, null=True)),
                ('stage_03', models.TextField(blank=True, null=True)),
                ('stage_04', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_stage_results', to='ai_workspace.task')),
            ],
        ),
    ]
