# Generated by Django 3.2.12 on 2025-05-20 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0039_taskstageresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstageresults',
            name='celery_task_batch',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskstageresults',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_stage_results', to='ai_workspace.task'),
        ),
    ]
