# Generated by Django 3.2.12 on 2025-05-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0040_auto_20250520_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstageresults',
            name='group_text_units',
            field=models.BooleanField(default=False),
        ),
    ]
