# Generated by Django 3.2.12 on 2025-05-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0041_taskstageresults_group_text_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracksegmentsbatchstatus',
            name='celery_task_batch',
            field=models.IntegerField(default=1),
        ),
    ]
