# Generated by Django 3.2.12 on 2025-05-20 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0042_tracksegmentsbatchstatus_celery_task_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstageresults',
            name='stage_02',
        ),
        migrations.RemoveField(
            model_name='taskstageresults',
            name='stage_03',
        ),
        migrations.RemoveField(
            model_name='taskstageresults',
            name='stage_04',
        ),
        migrations.CreateModel(
            name='AllStageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_02', models.TextField(blank=True, null=True)),
                ('stage_03', models.TextField(blank=True, null=True)),
                ('stage_04', models.TextField(blank=True, null=True)),
                ('task_stage_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_workspace.taskstageresults')),
            ],
        ),
    ]
