# Generated by Django 3.2.12 on 2025-05-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0044_alter_allstageresult_task_stage_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskstageresults',
            old_name='stage_01',
            new_name='style_guide_stage_1',
        ),
        migrations.AddField(
            model_name='allstageresult',
            name='source_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
