# Generated by Django 3.2.12 on 2025-05-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0045_auto_20250521_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='allstageresult',
            name='stage_2_input_token',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='allstageresult',
            name='stage_2_output_token',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='allstageresult',
            name='stage_3_input_token',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='allstageresult',
            name='stage_3_output_token',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='allstageresult',
            name='stage_4_input_token',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='allstageresult',
            name='stage_4_output_token',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
