# Generated by Django 3.2.12 on 2025-05-26 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0046_auto_20250522_0458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allstageresult',
            old_name='stage_02',
            new_name='stage_2',
        ),
        migrations.RenameField(
            model_name='allstageresult',
            old_name='stage_03',
            new_name='stage_3',
        ),
        migrations.RenameField(
            model_name='allstageresult',
            old_name='stage_04',
            new_name='stage_4',
        ),
    ]
