# Generated by Django 3.2.12 on 2025-06-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0047_auto_20250526_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='allstageresult',
            name='glossary_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
