# Generated by Django 3.2.12 on 2025-06-11 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0048_allstageresult_glossary_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstageresults',
            name='style_guide_stage_1',
        ),
        migrations.CreateModel(
            name='TaskStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_guide_stage_1', models.TextField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_style', to='ai_workspace.task')),
            ],
        ),
    ]
