# Generated by Django 3.2.12 on 2025-06-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0049_auto_20250611_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskstyle',
            old_name='style_guide_stage_1',
            new_name='status',
        ),
        migrations.AddField(
            model_name='taskstyle',
            name='style_guide',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskstyle',
            name='style_input_token',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='taskstyle',
            name='style_output_token',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
