# Generated by Django 3.2.12 on 2025-06-19 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0050_auto_20250611_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstageresults',
            name='segment_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_result_batch', to='ai_workspace.tracksegmentsbatchstatus'),
        ),
    ]
