# Generated by Django 3.2.12 on 2025-06-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0051_taskstageresults_segment_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='allstageresult',
            name='stage_2_error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allstageresult',
            name='stage_2_error_type',
            field=models.CharField(blank=True, choices=[('INSUFFICIENT_CREDIT', 'INSUFFICIENT_CREDIT'), ('LLM_ERROR', 'LLM_ERROR'), ('OTHER', 'OTHER')], default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='allstageresult',
            name='stage_3_error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allstageresult',
            name='stage_3_error_type',
            field=models.CharField(blank=True, choices=[('INSUFFICIENT_CREDIT', 'INSUFFICIENT_CREDIT'), ('LLM_ERROR', 'LLM_ERROR'), ('OTHER', 'OTHER')], default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='allstageresult',
            name='stage_4_error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allstageresult',
            name='stage_4_error_type',
            field=models.CharField(blank=True, choices=[('INSUFFICIENT_CREDIT', 'INSUFFICIENT_CREDIT'), ('LLM_ERROR', 'LLM_ERROR'), ('OTHER', 'OTHER')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tracksegmentsbatchstatus',
            name='error_type',
            field=models.CharField(blank=True, choices=[('INSUFFICIENT_CREDIT', 'INSUFFICIENT_CREDIT'), ('LLM_ERROR', 'LLM_ERROR'), ('OTHER', 'OTHER')], default=None, max_length=30, null=True),
        ),
    ]
