# Generated by Django 3.2.12 on 2025-06-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0052_auto_20250621_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='allstageresult',
            name='no_of_stages_used',
            field=models.IntegerField(default=3),
        ),
    ]
