# Generated by Django 3.2.12 on 2025-06-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0053_allstageresult_no_of_stages_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracksegmentsbatchstatus',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
