# Generated by Django 3.2.12 on 2025-06-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0054_tracksegmentsbatchstatus_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracksegmentsbatchstatus',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
