# Generated by Django 3.2.12 on 2025-11-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0055_tracksegmentsbatchstatus_retry_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedStyleGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('style_guide_content', models.TextField()),
            ],
        ),
    ]
