# Generated by Django 3.2.12 on 2025-11-23 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_staff', '0024_rename_systemprompt_adaptivesystemprompt'),
        ('ai_workspace', '0056_predefinedstyleguide'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinistryName',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('location', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PIBStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('headline', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('dateline', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ministry_department', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_workspace.ministryname')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pib_stories', to='ai_workspace.project')),
            ],
        ),
        migrations.CreateModel(
            name='MinistryTranslateName',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('translate_name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('languages_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministry_languages', to='ai_staff.languages')),
                ('ministry_name_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ministry_languages', to='ai_workspace.ministryname')),
            ],
            options={
                'ordering': ['translate_name'],
            },
        ),
        migrations.AddIndex(
            model_name='ministryname',
            index=models.Index(fields=['name'], name='ai_workspac_name_4e956b_idx'),
        ),
        migrations.AddIndex(
            model_name='ministrytranslatename',
            index=models.Index(fields=['translate_name'], name='ai_workspac_transla_4e4a0c_idx'),
        ),
    ]
