# Generated by Django 3.2.12 on 2025-11-23 08:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0057_auto_20251123_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPibDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_json', models.JSONField(blank=True, null=True)),
                ('target_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pib_task', to='ai_workspace.task')),
            ],
        ),
    ]
