# Generated by Django 3.2.12 on 2025-11-23 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0058_taskpibdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpibdetails',
            name='pib_story',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ai_workspace.pibstory'),
            preserve_default=False,
        ),
    ]
