# Generated by Django 3.2.12 on 2025-11-23 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0059_taskpibdetails_pib_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pibstory',
            name='ministry_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_workspace.ministryname'),
        ),
    ]
