# Generated by Django 3.2.12 on 2025-11-26 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0024_rename_systemprompt_adaptivesystemprompt'),
        ('ai_workspace', '0060_alter_pibstory_ministry_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskNewsPIBMT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt_raw_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('mt_engine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_news_pib_mt', to='ai_staff.ailaysasupportedmtpeengines')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasknews', to='ai_workspace.taskpibdetails')),
            ],
        ),
    ]
