# Generated by Django 3.2.12 on 2025-11-26 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0061_tasknewspibmt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasknewspibmt',
            name='task',
        ),
        migrations.AddField(
            model_name='tasknewspibmt',
            name='task_pib_detail',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tasknewspibdetail', to='ai_workspace.taskpibdetails'),
            preserve_default=False,
        ),
    ]
