# Generated by Django 3.2.12 on 2025-11-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0062_auto_20251126_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasknewspibmt',
            name='mt_raw_json',
            field=models.JSONField(null=True),
        ),
    ]
