# Generated by Django 3.2.12 on 2025-11-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0063_alter_tasknewspibmt_mt_raw_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpibdetails',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='Celery async task ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taskpibdetails',
            name='status',
            field=models.CharField(choices=[('YET_TO_START', 'yet_to_start'), ('In_Progress', 'in_progress'), ('COMPLETED', 'completed'), ('FAILED', 'failed')], default='YET_TO_START', max_length=20),
        ),
    ]
