# Generated by Django 3.2.12 on 2025-12-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0065_pibstyleguide'),
    ]

    operations = [
        migrations.AddField(
            model_name='pibstory',
            name='story_creation_type',
            field=models.CharField(choices=[('text_input', 'Text Input'), ('file_upload', 'File Upload')], default='text_input', max_length=50),
        ),
    ]
