# Generated by Django 3.2.12 on 2025-12-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workspace', '0066_pibstory_story_creation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pibstory',
            name='sub_headlines',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
