# Generated by Django 3.2.12 on 2025-12-16 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0024_rename_systemprompt_adaptivesystemprompt'),
        ('ai_workspace', '0067_pibstory_sub_headlines'),
    ]

    operations = [
        migrations.CreateModel(
            name='PIBSystemLanguagePrompts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pib_language', to='ai_staff.languages')),
            ],
        ),
    ]
