"""
Django settings for ai_tms project.

Generated by 'django-admin startproject' using Django 2.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import stripe

stripe.max_network_retries = 2


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..','..'))
TEMPLATE_DIR = os.path.join(BASE_DIR,'ai_staff','templates')
TEMPLATE_DIR_2 = os.path.join(BASE_DIR,'ai_vendor','templates')
TEMPLATE_DIR_3 = os.path.join(BASE_DIR,'ai_marketplace','templates')
TEMPLATE_DIR_4 = os.path.join(BASE_DIR,'ai_auth','templates')
TEMPLATE_DIR_5 = os.path.join(BASE_DIR,'ai_tms','templates')



CORS_ALLOW_METHODS = [
     'DELETE',
     'GET',
     'OPTIONS',
     'PATCH',
     'POST',
     'PUT',
]

CORS_ALLOW_HEADERS = [
     'accept',
     'accept-encoding',
     'authorization',
     'content-type',
     'dnt',
     'origin',
     'user-agent',
     'x-csrftoken',
     'x-requested-with',
     'Access-Control-Allow-Origin',
     'Access-Control-Allow-Credentials',
     'Access-Control-Allow-Headers',
     'cache',
     'cookie',
     'Access-Control-Expose-Headers',
     'responseType',
     'redirect',
]

CSRF_TRUSTED_ORIGINS = []

# Application definition

INSTALLED_APPS = [
    'django_prometheus',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cacheops',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'ai_auth',
    'dj_rest_auth',
    'django.contrib.sites',
    #  "silk",
    'allauth',
    'ai_staff',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.google',
    "allauth.socialaccount.providers.twitter",
    "ai_auth.providers.proz",
    'dj_rest_auth.registration',
    'ai_vendor',
    'ai_workspace',
    "ai_workspace_okapi",
    'django_extensions',
    'sqlite3',
    'ai_marketplace',
    'ai_glex',
    'ai_nlp',
    'djstripe',
    'django_filters',
    'notifications',
    'storages',
    'django_celery_results',
    "ai_pay",
    "ai_qa",
    'django_oso',
    #"ai_tm_management",
    "ai_tm",
    'ai_exportpdf',
    'ai_openai',
    'simple_history',
    'ai_canvas',
    'ai_imagetranslation',
    "ai_bi",
    # "debug_toolbar",
    #"drf_yasg",
   
]


SITE_ID = 1#os.getenv('SITE_ID')

WSGI_APPLICATION = 'ai_tms.wsgi.application'
ASGI_APPLICATION = 'ai_tms.asgi.application'


MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'corsheaders.middleware.CorsPostCsrfMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'django.middleware.cache.UpdateCacheMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'silk.middleware.SilkyMiddleware',
    #'django.middleware.cache.FetchFromCacheMiddleware',
    # 'django.middleware.gzip.GZipMiddleware',
    'ai_auth.custom_middleware.CustomGZipMiddleware',
    # 'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware'
    
]

#SILKY_PYTHON_PROFILER = True


ROOT_URLCONF = 'ai_tms.urls'
AUTH_USER_MODEL="ai_auth.AiUser"
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR,TEMPLATE_DIR_2,TEMPLATE_DIR_3,TEMPLATE_DIR_4, TEMPLATE_DIR_5],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

DATA_UPLOAD_MAX_MEMORY_SIZE = 560242880
USE_GZIP=True
GZIP_CONTENT_TYPES = (
    'text/css',
    'text/javascript',
    'text/xml',
    'text/plain',
    'text/html',
    'application/json',
    'application/javascript',
)


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'ai_auth.authentication.MysqlBackend',
    'django.contrib.auth.backends.ModelBackend',
    'guardian.backends.ObjectPermissionBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

DJANGO_NOTIFICATIONS_CONFIG = {
      'USE_JSONFIELD': True,
}


REST_USE_JWT = True


JWT_AUTH_COOKIE = 'ailaysa-auth'
JWT_AUTH_REFRESH_COOKIE = 'ailaysa-refresh-token'

#JWT_AUTH_SAMESITE = None

REST_AUTH_REGISTER_SERIALIZERS = {
    'REGISTER_SERIALIZER': 'ai_auth.serializers.UserRegistrationSerializer',
}

REST_AUTH_SERIALIZERS = {
    'PASSWORD_RESET_SERIALIZER':'ai_auth.serializers.AiPasswordResetSerializer',
    'USER_DETAILS_SERIALIZER': 'ai_auth.serializers.AiUserDetailsSerializer',
    'PASSWORD_CHANGE_SERIALIZER': 'ai_auth.serializers.AiPasswordChangeSerializer',
    'LOGIN_SERIALIZER':'ai_auth.serializers.AiLoginSerializer',
}


ACCOUNT_ADAPTER = 'ai_auth.ai_adapter.MyAccountAdapter'



REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
          'dj_rest_auth.jwt_auth.JWTCookieAuthentication',
        #'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS':
        'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 12,
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
        #'rest_framework.permissions.AllowAny',
    ],
    # 'DEFAULT_THROTTLE_CLASSES': [
    # 'rest_framework.throttling.AnonRateThrottle',
    # 'rest_framework.throttling.UserRateThrottle'
    # ],
    # 'DEFAULT_THROTTLE_RATES': {
    #     'anon': '50/minute',
    #     'user': '100/minute'
    # }
}


# SOCIALACCOUNT_ADAPTER="ai_auth.ai_adapter.SocialAdapter"

SOCIALACCOUNT_PROVIDERS = {
    'github': {
        'SCOPE': [
            'user',
            'repo',
            'read:org',
        ],
    },
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'offline',
        }
    },
    'proz':{
              'SCOPE': [
            'public',
            'user.email',
            'user.name'
        ],
        'AUTH_PARAMS': {
            'access_type': 'offline',
        }  
    }
}



# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/



# ------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


OLD_PASSWORD_FIELD_ENABLED = True

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    }



STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]


# FONT_THUMBNAIL_ROOT = os.path.join(STATIC_ROOT, 'canvas-assets/font-thumnail')
# FONT_THUMBNAIL_URL = '/font-thumnail/'
#######
INPAINT_IMAGE_ROOT =  os.path.join(BASE_DIR, 'inpaint_image')
INPAINT_IMAGE_URL = '/inpaint_image/'

INPAINT_SOURCE_IMAGE_ROOT =  os.path.join(BASE_DIR, 'inpaint_source_image')
INPAINT_SOURCE_IMAGE_URL = '/inpaint_source_image/'

EXPORT_IMAGE_ROOT =  os.path.join(BASE_DIR, 'temp_download')
EXPORT_IMAGE_URL = '/temp_download/'
 
os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"
ADAPTIVE_TRANSLATE_LLM_MODEL_PIB = os.getenv('ADAPTIVE_TRANSLATE_LLM_MODEL_PIB')