# Generated by Django 3.2.12 on 2022-08-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0001_staff01'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionfeatures',
            name='sequence_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subscriptionfeatures',
            name='set_id',
            field=models.IntegerField(),
        ),
    ]
