# Generated by Django 3.2.4 on 2021-12-16 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0002_jobpositions_supporttopics'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageScripts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'language_scripts',
            },
        ),
        migrations.AddField(
            model_name='creditsaddons',
            name='expiry',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='LanguageMetaDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name_in_script', models.CharField(blank=True, max_length=200, null=True)),
                ('ime', models.BooleanField(blank=True, default=False, null=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language_meta_details', to='ai_staff.languages')),
                ('script', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='language_meta_details', to='ai_staff.languagescripts')),
            ],
            options={
                'db_table': 'language_meta_details',
            },
        ),
    ]
