# Generated by Django 3.2.12 on 2022-09-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0002_auto_20220818_0703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenttypes',
            options={'verbose_name_plural': 'Content_types'},
        ),
        migrations.RemoveField(
            model_name='mtlanguagelocalevoicesupport',
            name='has_female',
        ),
        migrations.RemoveField(
            model_name='mtlanguagelocalevoicesupport',
            name='has_male',
        ),
        migrations.AddField(
            model_name='mtlanguagelocalevoicesupport',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mtlanguagelocalevoicesupport',
            name='voice_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='mtlanguagelocalevoicesupport',
            name='voice_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
