# Generated by Django 3.2.12 on 2022-10-03 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0003_auto_20220909_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscribeSupportedPunctuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punctuation_locale', to='ai_staff.languageslocale')),
                ('mtpe_engines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punc_supported_mt', to='ai_staff.ailaysasupportedmtpeengines')),
            ],
        ),
    ]
