# Generated by Django 3.2.4 on 2022-02-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0004_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldVendorPasswords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='subscriptionfeatures',
            name='sequence_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionfeatures',
            name='set_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
