# Generated by Django 3.2.4 on 2022-06-16 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0005_auto_20220208_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTypeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('projecttype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_type_detail', to='ai_staff.projecttype')),
            ],
        ),
        migrations.CreateModel(
            name='MTLanguageSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speech_to_text', models.BooleanField(default=False)),
                ('text_to_speech', models.BooleanField(default=False)),
                ('translate', models.BooleanField(default=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supported_lang', to='ai_staff.languages')),
                ('mtpe_engines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supported_mt', to='ai_staff.ailaysasupportedmtpeengines')),
            ],
        ),
        migrations.CreateModel(
            name='MTLanguageLocaleVoiceSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_female', models.BooleanField(default=False)),
                ('has_male', models.BooleanField(default=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supported_language', to='ai_staff.languages')),
                ('language_locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supported_locale', to='ai_staff.languageslocale')),
                ('mtpe_engines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_mt', to='ai_staff.ailaysasupportedmtpeengines')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyBasedOnCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_country', to='ai_staff.countries')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_currency', to='ai_staff.currencies')),
            ],
        ),
    ]
