# Generated by Django 3.2.12 on 2023-12-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0010_auto_20231012_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptstartphrases',
            name='assistant',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
