# Generated by Django 3.2.12 on 2024-03-28 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0012_bookcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookCategory',
        ),
    ]
