# Generated by Django 3.2.12 on 2024-05-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0014_internalflowprompts'),
    ]

    operations = [
        migrations.AddField(
            model_name='levels',
            name='level_content',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
