# Generated by Django 3.2.12 on 2024-05-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0015_levels_level_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='levels',
            name='no_of_chapter_headings',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='levels',
            name='level_content',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
