# Generated by Django 3.2.12 on 2024-08-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0017_segmentchoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentchoices',
            name='option',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
