# Generated by Django 3.2.12 on 2024-08-29 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0019_delete_segmentchoices'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageGrammarPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_name', models.CharField(blank=True, max_length=300, null=True)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gram_prmpt_lang', to='ai_staff.languages')),
            ],
        ),
    ]
