# Generated by Django 3.2.12 on 2024-09-04 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0020_languagegrammarprompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraReplacePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(blank=True, null=True)),
                ('internal_prompt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='replace_internal_prmpt', to='ai_staff.internalflowprompts')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gextra_prmpt_lang', to='ai_staff.languages')),
            ],
        ),
    ]
