# Generated by Django 3.2.12 on 2024-09-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0021_extrareplaceprompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicustomize',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
