# Generated by Django 3.2.12 on 2025-05-09 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0023_systemprompt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SystemPrompt',
            new_name='AdaptiveSystemPrompt',
        ),
    ]
