# Generated by Django 3.2.12 on 2023-07-16 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bi_role', models.CharField(choices=[('TECHNICAL', 'TECHNICAL'), ('FINANCE', 'FINANCE'), ('ADMIN', 'ADMIN')], max_length=250)),
                ('bi_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bi_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
