# Generated by Django 3.2.12 on 2023-07-27 14:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ai_bi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiUserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fullname', models.CharField(blank=True, max_length=191, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivation_date', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('deactivate', models.BooleanField(default=False)),
                ('is_vendor', models.BooleanField(default=False)),
                ('is_agency', models.BooleanField(default=False)),
                ('is_internal_member', models.BooleanField(default=False)),
                ('first_login', models.BooleanField(default=False)),
                ('currency_based_on_country', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_name', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_status', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_start', models.DateTimeField(blank=True, null=True)),
                ('subscription_end', models.DateTimeField(blank=True, null=True)),
                ('intial_credits', models.IntegerField(default=0)),
                ('credits_left', models.IntegerField(default=0)),
                ('credits_consumed', models.IntegerField(default=0)),
                ('projects_created', models.IntegerField(default=0)),
                ('documents_created', models.IntegerField(default=0)),
                ('pdf_conversion', models.IntegerField(default=0)),
                ('blogs_created', models.IntegerField(default=0)),
                ('signup_age', models.IntegerField(default=0)),
                ('project_types', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsedLangPairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_lang', models.CharField(max_length=200)),
                ('target_lang', models.CharField(blank=True, max_length=200, null=True)),
                ('user_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lang_pair_used', to='ai_bi.aiuserdetails')),
            ],
        ),
    ]
