# Generated by Django 3.2.12 on 2024-09-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_bi', '0002_aiuserdetails_usedlangpairs'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiuserdetails',
            name='from_campaign',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
