# Generated by Django 3.2.12 on 2025-01-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_bi', '0003_aiuserdetails_from_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiuserdetails',
            name='project_types',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
