# Generated by Django 3.2.12 on 2022-08-17 14:38

import ai_auth.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('ai_auth', '0002_creditpack_officialinformation_personalinformation_usercredits'), ('ai_auth', '0003_auto_20210927_1220'), ('ai_auth', '0004_auto_20210928_0545'), ('ai_auth', '0005_alter_creditpack_product'), ('ai_auth', '0006_carriersupport_generalsupport_vendoronboarding'), ('ai_auth', '0007_auto_20211015_0936'), ('ai_auth', '0008_alter_contactpricing_description'), ('ai_auth', '0009_auto_20211021_1016'), ('ai_auth', '0010_auto_20211026_0617'), ('ai_auth', '0011_auto_20211026_0928'), ('ai_auth', '0012_aiuser_is_delete'), ('ai_auth', '0013_rename_is_delete_aiuser_deactivate'), ('ai_auth', '0014_alter_customersupport_description'), ('ai_auth', '0015_referredusers'), ('ai_auth', '0016_auto_20220120_1322'), ('ai_auth', '0017_auto_20220128_1142'), ('ai_auth', '0018_alter_hirededitors_date_of_expiry'), ('ai_auth', '0019_auto_20220208_0854'), ('ai_auth', '0020_auto_20220222_1206'), ('ai_auth', '0021_alter_hirededitors_date_of_expiry'), ('ai_auth', '0022_alter_hirededitors_date_of_expiry'), ('ai_auth', '0023_alter_hirededitors_date_of_expiry'), ('ai_auth', '0024_auto_20220616_1437'), ('ai_auth', '0025_auto_20220623_1024'), ('ai_auth', '0026_auto_20220629_1247'), ('ai_auth', '0027_auto_20220714_0708'), ('ai_auth', '0028_auto_20220811_1144')]

    dependencies = [
        ('ai_staff', '0004_role'),
        ('ai_staff', '0002_jobpositions_supporttopics'),
        ('ai_auth', '0001_initial'),
        ('djstripe', '0008_2_5'),
        ('ai_staff', '0006_currencybasedoncountry_mtlanguagelocalevoicesupport_mtlanguagesupport_projecttype_projecttypedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCredits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_id', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('buyed_credits', models.IntegerField()),
                ('credits_left', models.IntegerField()),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.CharField(blank=True, max_length=200, null=True)),
                ('paymentintent', models.CharField(blank=True, max_length=200, null=True)),
                ('credit_pack_type', models.CharField(blank=True, max_length=200, null=True)),
                ('stripe_cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djstripe.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('credits', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djstripe.product')),
            ],
        ),
        migrations.CreateModel(
            name='CarrierSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phonenumber', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(default='', max_length=1000)),
                ('cv_file', models.FileField(default='', upload_to=ai_auth.models.file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('job_position', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ai_staff.jobpositions')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phonenumber', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(default='', max_length=1000)),
                ('support_file', models.FileField(blank=True, null=True, upload_to=ai_auth.models.support_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('topic', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ai_staff.supporttopics')),
            ],
        ),
        migrations.CreateModel(
            name='VendorOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('cv_file', models.FileField(default='', upload_to=ai_auth.models.file_path_vendor)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('message', models.TextField(blank=True, max_length=1000, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Request Sent'), (2, 'Accepted'), (3, 'Hold'), (4, 'Waitlisted')])),
            ],
        ),
        migrations.AlterField(
            model_name='contactpricing',
            name='description',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='zipcode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='zipcode',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='aiuser',
            name='deactivation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='zipcode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aiuser',
            name='deactivate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customersupport',
            name='description',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ReferredUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterModelOptions(
            name='userattribute',
            options={'managed': True, 'permissions': (('user-attribute-exist', 'user attribute exist'),)},
        ),
        migrations.AddField(
            model_name='aiuser',
            name='is_internal_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiuser',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InternalMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('functional_identity', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Credentials Sent'), (2, 'Logged In')])),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_team_manager', to=settings.AUTH_USER_MODEL)),
                ('internal_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_member', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_role', to='ai_staff.role')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_member_team_info', to='ai_auth.team')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_campaign', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HiredEditors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Invite Sent'), (2, 'Invite Accepted')])),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_team_manager', to=settings.AUTH_USER_MODEL)),
                ('hired_editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hired_editor', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_staff.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL)),
                ('date_of_expiry', models.DateField(blank=True, default=datetime.date(2022, 7, 6))),
                ('date_of_link_sent', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('user', 'hired_editor', 'role')},
            },
        ),
        migrations.CreateModel(
            name='ExistingVendorOnboardingCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_password', models.CharField(max_length=255)),
                ('mail_sent', models.BooleanField(default=False)),
                ('mail_sent_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existing_vendor_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocStates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=150, unique=True)),
                ('data', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
