# Generated by Django 3.2.4 on 2021-09-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auth', '0002_creditpack_officialinformation_personalinformation_usercredits'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredits',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercredits',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
