# Generated by Django 3.2.12 on 2022-08-18 07:03

import ai_auth.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0002_auto_20220818_0703'),
        ('ai_auth', '0002_second_mig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carriersupport',
            name='cv_file',
            field=models.FileField(upload_to=ai_auth.models.file_path),
        ),
        migrations.AlterField(
            model_name='carriersupport',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='carriersupport',
            name='job_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_staff.jobpositions'),
        ),
        migrations.AlterField(
            model_name='carriersupport',
            name='message',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='generalsupport',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='generalsupport',
            name='message',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='generalsupport',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_staff.supporttopics'),
        ),
        migrations.AlterField(
            model_name='hirededitors',
            name='date_of_expiry',
            field=models.DateField(blank=True, default=datetime.date(2022, 8, 25)),
        ),
        migrations.AlterField(
            model_name='vendoronboarding',
            name='cv_file',
            field=models.FileField(upload_to=ai_auth.models.file_path_vendor),
        ),
        migrations.AlterField(
            model_name='vendoronboarding',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
