# Generated by Django 3.2.4 on 2021-09-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auth', '0003_auto_20210927_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercredits',
            old_name='Buyed_credits',
            new_name='buyed_credits',
        ),
        migrations.AlterField(
            model_name='usercredits',
            name='credits_left',
            field=models.IntegerField(),
        ),
    ]
