# Generated by Django 3.2.12 on 2022-09-13 10:11

import ai_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auth', '0003_auto_20220818_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredits',
            name='carried_credits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hirededitors',
            name='date_of_expiry',
            field=models.DateField(blank=True, default=ai_auth.models.default_date_hired_editor_expiry),
        ),
    ]
