# Generated by Django 3.2.4 on 2021-10-11 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0008_2_5'),
        ('ai_auth', '0004_auto_20210928_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpack',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djstripe.product'),
        ),
    ]
