# Generated by Django 3.2.12 on 2022-09-29 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0003_auto_20220909_1147'),
        ('ai_auth', '0004_auto_20220913_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiuser',
            name='currency_based_on_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aiuser_country_based_currency', to='ai_staff.currencies'),
        ),
    ]
