# Generated by Django 3.2.4 on 2021-10-13 11:43

import ai_auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0002_jobpositions_supporttopics'),
        ('ai_auth', '0005_alter_creditpack_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to=ai_auth.models.file_path_vendor)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, max_length=1000, null=True)),
                ('support_file', models.FileField(blank=True, null=True, upload_to=ai_auth.models.support_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_staff.supporttopics')),
            ],
        ),
        migrations.CreateModel(
            name='CarrierSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, max_length=1000, null=True)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to=ai_auth.models.file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('job_positions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_staff.jobpositions')),
            ],
        ),
    ]
