# Generated by Django 3.2.12 on 2022-10-19 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auth', '0005_aiuser_currency_based_on_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='AilaysaCampaigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=100, unique=True)),
                ('subscription_name', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_duration', models.CharField(blank=True, choices=[('month', 'month'), ('year', 'year')], max_length=100, null=True)),
                ('subscription_intervals', models.IntegerField(default=1)),
                ('subscription_credits', models.IntegerField()),
                ('Addon_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Addon_quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='campaignusers',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campaignusers',
            name='campaign_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ai_campaigns', to='ai_auth.ailaysacampaigns'),
            preserve_default=False,
        ),
    ]
