# Generated by Django 3.2.4 on 2021-10-15 09:36

import ai_auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0002_jobpositions_supporttopics'),
        ('ai_auth', '0006_carriersupport_generalsupport_vendoronboarding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carriersupport',
            name='job_positions',
        ),
        migrations.AddField(
            model_name='carriersupport',
            name='job_position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ai_staff.jobpositions'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carriersupport',
            name='cv_file',
            field=models.FileField(default='', upload_to=ai_auth.models.file_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carriersupport',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carriersupport',
            name='message',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='generalsupport',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='generalsupport',
            name='message',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='generalsupport',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ai_staff.supporttopics'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendoronboarding',
            name='cv_file',
            field=models.FileField(default='', upload_to=ai_auth.models.file_path_vendor),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendoronboarding',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendoronboarding',
            name='name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
