# Generated by Django 3.2.12 on 2023-02-24 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0006_auto_20230224_0622'),
        ('ai_auth', '0006_auto_20221019_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpack',
            name='expires_at',
            field=models.IntegerField(blank=True, help_text='no of months', null=True),
        ),
        migrations.CreateModel(
            name='TaskRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_pk', models.CharField(max_length=255, verbose_name='Task ID')),
                ('proj_pk', models.CharField(max_length=255, verbose_name='Project ID')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_roles', to='ai_staff.taskrolelevel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_task_roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_pk', models.CharField(max_length=255, verbose_name='Project ID')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_roles', to='ai_staff.projectrolelevel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_project_roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalApiUsage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uid', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('usage', models.IntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ai_staff.apiservicelist')),
            ],
            options={
                'verbose_name': 'historical api usage',
                'verbose_name_plural': 'historical api usages',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ApiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('usage', models.IntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_service_list', to='ai_staff.apiservicelist')),
            ],
        ),
        migrations.AddConstraint(
            model_name='taskroles',
            constraint=models.UniqueConstraint(fields=('role', 'user', 'task_pk'), name='unique_task_roles'),
        ),
        migrations.AddConstraint(
            model_name='projectroles',
            constraint=models.UniqueConstraint(fields=('role', 'user', 'proj_pk'), name='unique_project_roles'),
        ),
        migrations.AddConstraint(
            model_name='apiusage',
            constraint=models.UniqueConstraint(fields=('uid', 'email', 'service'), name='unique_user_usage'),
        ),
    ]
