# Generated by Django 3.2.12 on 2023-03-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auth', '0007_auto_20230224_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='temppricingpreference',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
