# Generated by Django 3.2.4 on 2021-10-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auth', '0007_auto_20211015_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpricing',
            name='description',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
