# Generated by Django 3.2.4 on 2021-10-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auth', '0008_alter_contactpricing_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfficialInformation',
        ),
        migrations.DeleteModel(
            name='PersonalInformation',
        ),
        migrations.AddField(
            model_name='aiuser',
            name='deactivation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='zipcode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
