# Generated by Django 3.2.12 on 2023-06-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auth', '0008_temppricingpreference_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiuser',
            name='is_agency',
            field=models.BooleanField(default=False),
        ),
    ]
