# Generated by Django 3.2.4 on 2021-10-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auth', '0009_auto_20211021_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'official_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(blank=True, max_length=255, null=True)),
                ('mobilenumber', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'personal_info',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='aiuser',
            name='deactivation_date',
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='zipcode',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
