# Generated by Django 3.2.12 on 2023-06-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auth', '0009_aiuser_is_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiuser',
            name='first_login',
            field=models.BooleanField(default=False),
        ),
    ]
