# Generated by Django 3.2.12 on 2023-07-06 12:03

import ai_auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0008_suggestion_suggestiontype'),
        ('ai_auth', '0010_aiuser_first_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoCreateForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(max_length=5000)),
                ('app_suggestion_file', models.FileField(blank=True, null=True, upload_to=ai_auth.models.cocreate_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_staff.suggestion')),
                ('suggestion_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_staff.suggestiontype')),
            ],
        ),
    ]
