# Generated by Django 3.2.4 on 2021-10-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auth', '0011_auto_20211026_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiuser',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
