# Generated by Django 3.2.12 on 2023-07-16 08:30

import ai_auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auth', '0011_cocreateform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocreateform',
            name='app_suggestion_file',
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='CoCreateFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_suggestion_file', models.FileField(blank=True, null=True, upload_to=ai_auth.models.cocreate_file_path)),
                ('co_create', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cocreate_file', to='ai_auth.cocreateform')),
            ],
        ),
    ]
