# Generated by Django 3.2.4 on 2021-10-30 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auth', '0012_aiuser_is_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aiuser',
            old_name='is_delete',
            new_name='deactivate',
        ),
    ]
