# Generated by Django 3.2.12 on 2023-08-16 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0015_alter_payout_failure_code'),
        ('ai_auth', '0012_auto_20230716_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='ailaysacampaigns',
            name='coupon',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='campaignusers',
            name='coupon_used',
            field=models.BooleanField(null=True),
        ),
        migrations.CreateModel(
            name='SubscriptionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('higher_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_order_product_up', to='djstripe.product')),
                ('lower_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_order_product_lw', to='djstripe.product')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_order_product', to='djstripe.product')),
            ],
        ),
        migrations.AddConstraint(
            model_name='subscriptionorder',
            constraint=models.UniqueConstraint(fields=('plan', 'lower_plan', 'higher_plan'), name='subscriptins_order'),
        ),
    ]
