# Generated by Django 3.2.12 on 2023-09-30 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auth', '0013_auto_20230816_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='TroubleshootIssues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=200)),
                ('issue_desc', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='aiuser',
            name='need_fix',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AiTroubleshootData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='troubleshoot_issues', to='ai_auth.troubleshootissues')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='troubleshoot_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
