# Generated by Django 3.2.4 on 2021-11-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auth', '0013_rename_is_delete_aiuser_deactivate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersupport',
            name='description',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
