# Generated by Django 3.2.12 on 2023-10-12 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0015_alter_payout_failure_code'),
        ('ai_auth', '0014_auto_20230930_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dj_stripe_price_id', models.CharField(blank=True, max_length=200, null=True)),
                ('purchase_pack_type', models.CharField(blank=True, max_length=200, null=True)),
                ('units_buyed', models.IntegerField()),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.CharField(blank=True, max_length=200, null=True)),
                ('paymentintent', models.CharField(blank=True, max_length=200, null=True)),
                ('recurring', models.CharField(blank=True, choices=[('daily', 'Renew Daily'), ('monthly', 'Renew Monthly')], max_length=100, null=True)),
                ('purchased', models.BooleanField(default=False)),
                ('buyed_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='creditpack',
            name='recurring',
            field=models.CharField(blank=True, choices=[('daily', 'Renew Daily'), ('monthly', 'Renew Monthly')], max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='creditpack',
            name='secondary_credits',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='creditpack',
            name='secondary_recurring',
            field=models.CharField(blank=True, choices=[('daily', 'Renew Daily'), ('monthly', 'Renew Monthly')], max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='creditpack',
            name='secondary_unit_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='creditpack',
            name='unit_type',
            field=models.CharField(default='credits', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercredits',
            name='price_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='PurchasedUnitsCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ailaysa_service', models.CharField(max_length=150)),
                ('intial_units', models.IntegerField(default=0)),
                ('units_left', models.IntegerField(default=0)),
                ('unit_type', models.CharField(max_length=100)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('purchase_units', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_purchased_units', to='ai_auth.purchasedunits')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='purchasedunits',
            name='purchase_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_units_cp', to='ai_auth.creditpack'),
        ),
        migrations.AddField(
            model_name='purchasedunits',
            name='stripe_cust_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.customer'),
        ),
        migrations.AddField(
            model_name='purchasedunits',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PdfChatUsageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_threshold', models.IntegerField(default=0)),
                ('no_of_question_remaining', models.IntegerField(default=0)),
                ('add_on_subscribed', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
