# Generated by Django 3.2.4 on 2021-12-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auth', '0014_alter_customersupport_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferredUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
