# Generated by Django 3.2.12 on 2023-11-02 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auth', '0015_auto_20231012_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredits',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_credits', to=settings.AUTH_USER_MODEL),
        ),
    ]
