# Generated by Django 3.2.4 on 2022-01-20 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0004_role'),
        ('ai_auth', '0015_referredusers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userattribute',
            options={'managed': True, 'permissions': (('user-attribute-exist', 'user attribute exist'),)},
        ),
        migrations.AddField(
            model_name='aiuser',
            name='is_internal_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiuser',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendoronboarding',
            name='message',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='vendoronboarding',
            name='status',
            field=models.IntegerField(choices=[(1, 'Request Sent'), (2, 'Accepted'), (3, 'Hold'), (4, 'Rejected')], default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InternalMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('functional_identity', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Credentials Sent'), (2, 'Logged In')])),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_team_manager', to=settings.AUTH_USER_MODEL)),
                ('internal_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_member', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_role', to='ai_staff.role')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_member_team_info', to='ai_auth.team')),
            ],
        ),
        migrations.CreateModel(
            name='HiredEditors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Invite Sent'), (2, 'Invite Accepted')])),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_team_manager', to=settings.AUTH_USER_MODEL)),
                ('hired_editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hired_editor', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_staff.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'hired_editor', 'role')},
            },
        ),
    ]
