# Generated by Django 3.2.12 on 2023-11-24 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auth', '0016_alter_usercredits_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiuser',
            name='is_enterprise',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EnterpriseUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_enterprise', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
