# Generated by Django 3.2.4 on 2022-01-28 11:42

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auth', '0016_auto_20220120_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirededitors',
            name='date_of_expiry',
            field=models.DateField(blank=True, default=datetime.date(2022, 2, 4)),
        ),
        migrations.AddField(
            model_name='hirededitors',
            name='date_of_link_sent',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vendoronboarding',
            name='rejected_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendoronboarding',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
