# Generated by Django 3.2.4 on 2022-02-08 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auth', '0017_auto_20220128_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirededitors',
            name='date_of_expiry',
            field=models.DateField(blank=True, default=datetime.date(2022, 2, 15)),
        ),
    ]
