# Generated by Django 3.2.12 on 2023-12-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auth', '0017_auto_20231124_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingBootcamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('job_interest', models.BooleanField(default=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='bootcamp_marketing_resume_file')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
