# Generated by Django 3.2.4 on 2022-02-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auth', '0018_alter_hirededitors_date_of_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendoronboarding',
            name='rejected_count',
        ),
        migrations.AlterField(
            model_name='vendoronboarding',
            name='status',
            field=models.IntegerField(choices=[(1, 'Request Sent'), (2, 'Accepted'), (3, 'Hold'), (4, 'Waitlisted')]),
        ),
    ]
