# Generated by Django 3.2.12 on 2024-02-08 08:40

import ai_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auth', '0018_marketingbootcamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerSupportAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('college', models.TextField(blank=True, max_length=1000, null=True)),
                ('apply_for', models.IntegerField(choices=[(1, 'Internship'), (2, 'Job'), (3, 'Project')])),
                ('cv_file', models.FileField(upload_to=ai_auth.models.file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
