# Generated by Django 3.2.12 on 2024-02-08 10:55

import ai_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auth', '0019_careersupportai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careersupportai',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to=ai_auth.models.file_path),
        ),
    ]
