# Generated by Django 3.2.4 on 2022-03-03 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auth', '0020_auto_20220222_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirededitors',
            name='date_of_expiry',
            field=models.DateField(blank=True, default=datetime.date(2022, 3, 10)),
        ),
    ]
