# Generated by Django 3.2.12 on 2024-03-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auth', '0020_alter_careersupportai_cv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_member_count',
            field=models.IntegerField(default=0),
        ),
    ]
