# Generated by Django 3.2.12 on 2024-04-18 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auth', '0021_team_team_member_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='AilaysaCallCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('service_type', models.CharField(blank=True, max_length=100, null=True)),
                ('source_language', models.CharField(blank=True, max_length=25, null=True)),
                ('target_language', models.CharField(blank=True, max_length=25, null=True)),
                ('service_description', models.CharField(blank=True, max_length=600, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AilaysaCallCenterFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='ailaysa_call_center')),
                ('ailaysa_call_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ailaysa_call_ctr', to='ai_auth.ailaysacallcenter')),
            ],
        ),
    ]
