# Generated by Django 3.2.12 on 2025-01-10 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0022_alter_aicustomize_prompt'),
        ('ai_auth', '0022_ailaysacallcenter_ailaysacallcenterfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AilaysaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('industry', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=75)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_events_country', to='ai_staff.countries')),
            ],
        ),
    ]
