# Generated by Django 3.2.4 on 2022-04-29 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auth', '0022_alter_hirededitors_date_of_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirededitors',
            name='date_of_expiry',
            field=models.DateField(blank=True, default=datetime.date(2022, 5, 6)),
        ),
    ]
