# Generated by Django 3.2.4 on 2022-06-16 14:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auth', '0023_alter_hirededitors_date_of_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirededitors',
            name='date_of_expiry',
            field=models.DateField(blank=True, default=datetime.date(2022, 6, 23)),
        ),
    ]
