# Generated by Django 3.2.12 on 2025-01-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auth', '0023_ailaysaevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ailaysaevent',
            name='industry',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
