# Generated by Django 3.2.12 on 2025-01-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auth', '0024_alter_ailaysaevent_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ailaysaevent',
            name='email',
            field=models.EmailField(max_length=300),
        ),
    ]
