# Generated by Django 3.2.4 on 2022-06-23 10:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0006_currencybasedoncountry_mtlanguagelocalevoicesupport_mtlanguagesupport_projecttype_projecttypedetail'),
        ('ai_auth', '0024_auto_20220616_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistingVendorOnboardingCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_password', models.CharField(max_length=255)),
                ('mail_sent', models.BooleanField(default=False)),
                ('mail_sent_time', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existing_vendor_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
