# Generated by Django 3.2.4 on 2022-06-29 12:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0006_currencybasedoncountry_mtlanguagelocalevoicesupport_mtlanguagesupport_projecttype_projecttypedetail'),
        ('ai_auth', '0025_auto_20220623_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirededitors',
            name='date_of_expiry',
            field=models.DateField(blank=True, default=datetime.date(2022, 7, 6)),
        ),
    ]
