# Generated by Django 3.2.12 on 2025-01-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auth', '0025_alter_ailaysaevent_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ailaysaevent',
            name='service_needed',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
