# Generated by Django 3.2.12 on 2025-04-10 14:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auth', '0026_ailaysaevent_service_needed'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoUserFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('AILAYSA', 'Ailaysa'), ('CHATBOOK', 'Chatbook')], default='AILAYSA', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
