# Generated by Django 3.2.4 on 2022-07-14 07:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auth', '0026_auto_20220629_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existingvendoronboardingcheck',
            name='mail_sent_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
