# Generated by Django 3.2.4 on 2022-08-11 11:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auth', '0027_auto_20220714_0708'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocStates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=150, unique=True)),
                ('data', models.CharField(blank=True, max_length=255, null=True)),
            ],
        )
    ]
