# Generated by Django 3.2.12 on 2025-04-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auth', '0027_demouserformsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demouserformsubmission',
            name='source',
            field=models.CharField(choices=[('ailaysa', 'AILAYSA'), ('chatbook', 'CHATBOOK')], default='ailaysa', max_length=20),
        ),
    ]
