# Generated by Django 3.2.12 on 2025-11-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_auth', '0028_alter_demouserformsubmission_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiuser',
            name='is_pib',
            field=models.BooleanField(default=False),
        ),
    ]
