# Generated by Django 3.2.12 on 2023-10-12 17:40

import ai_nlp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PdffileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=ai_nlp.models.user_directory_path_pdf_upload)),
                ('file_name', models.CharField(blank=True, max_length=200, null=True)),
                ('pdf_thumbnail', models.FileField(blank=True, null=True, upload_to=ai_nlp.models.user_directory_path_pdf_thumbnail)),
                ('vector_embedding_path', models.CharField(blank=True, max_length=200, null=True)),
                ('is_train', models.BooleanField(default=False)),
                ('vector_id', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('celery_id', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('text_file', models.FileField(blank=True, null=True, upload_to=ai_nlp.models.user_directory_path_pdf_upload)),
                ('website', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdfchat_created_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PdffileChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=2000, null=True)),
                ('answer', models.CharField(blank=True, max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token_usage', models.CharField(blank=True, max_length=2000, null=True)),
                ('pdf_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_file_chat', to='ai_nlp.pdffileupload')),
            ],
        ),
    ]
