# Generated by Django 3.2.12 on 2023-11-24 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_nlp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfQustion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=500, null=True)),
                ('pdf_file_chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdf_file_question', to='ai_nlp.pdffileupload')),
            ],
        ),
    ]
