# Generated by Django 3.2.12 on 2023-12-21 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0011_promptstartphrases_assistant'),
        ('ai_nlp', '0002_pdfqustion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffilechathistory',
            name='answer_mt',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='pdffilechathistory',
            name='question_mt',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='pdffileupload',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdf_chat_lang', to='ai_staff.languages'),
        ),
    ]
