# Generated by Django 3.2.12 on 2024-02-20 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_staff', '0011_promptstartphrases_assistant'),
        ('ai_nlp', '0003_auto_20231221_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdffileupload',
            name='language',
        ),
        migrations.AddField(
            model_name='pdffilechathistory',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdf_chat_lang', to='ai_staff.languages'),
        ),
    ]
