# Generated by Django 3.2.12 on 2024-02-29 12:32

import ai_nlp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_nlp', '0004_auto_20240220_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=ai_nlp.models.user_directory_path_public_pdf)),
                ('file_name', models.CharField(blank=True, max_length=200, null=True)),
                ('author', models.CharField(blank=True, max_length=500, null=True)),
                ('isbn', models.CharField(blank=True, max_length=14, null=True)),
                ('pdf_thumbnail', models.FileField(blank=True, null=True, upload_to=ai_nlp.models.user_directory_pdf_publicbook_thumbnail)),
                ('vector_embedding_path', models.CharField(blank=True, max_length=200, null=True)),
                ('text_file', models.FileField(blank=True, null=True, upload_to=ai_nlp.models.user_directory_path_pdf_upload)),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('celery_id', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_public_created_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
