# Generated by Django 3.2.12 on 2024-04-18 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_nlp', '0005_publicbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPageReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_no', models.IntegerField(blank=True, null=True)),
                ('pdf_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_chat_page_ref', to='ai_nlp.pdffilechathistory')),
            ],
        ),
    ]
