# Generated by Django 3.2.12 on 2025-08-19 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_nlp', '0007_embeddingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffileupload',
            name='embedding_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdf_embed_chat', to='ai_nlp.embeddingmodel'),
        ),
    ]
