# Generated by Django 3.2.12 on 2025-12-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_nlp', '0008_pdffileupload_embedding_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffilechathistory',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdffilechathistory',
            name='answer_mt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdffilechathistory',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdffilechathistory',
            name='question_mt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
