# Generated by Django 3.2.4 on 2021-09-27 08:08

import ai_vendor.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorLanguagePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('source_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_source_lang', to='ai_staff.languages')),
                ('target_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_target_lang', to='ai_staff.languages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_lang_pair', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorSubjectFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_subject', to='ai_staff.subjectfields')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_subject', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VendorsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_unique_id', models.CharField(blank=True, max_length=191, null=True)),
                ('vm_status', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('token', models.CharField(blank=True, max_length=191, null=True)),
                ('skype', models.CharField(blank=True, max_length=191, null=True)),
                ('proz_link', models.CharField(blank=True, max_length=191, null=True)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to=ai_vendor.models.vendor_directory_path)),
                ('year_of_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_currency', to='ai_staff.currencies')),
                ('native_lang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='native_lang', to='ai_staff.languages')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_legal_type', to='ai_staff.vendorlegalcategories')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorServiceTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('unit_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('minute_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('lang_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicetype', to='ai_vendor.vendorlanguagepair')),
                ('services', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='ai_staff.servicetypes')),
                ('unit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_staff.servicetypeunits')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VendorServiceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('mtpe_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mtpe_hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('lang_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='ai_vendor.vendorlanguagepair')),
                ('mtpe_count_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_type', to='ai_staff.servicetypeunits')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VendorMtpeEngines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('mtpe_engines', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_mtpe_engines', to='ai_staff.mtpeengines')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_mtpe_engines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VendorMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_membership', to='ai_staff.vendormemberships')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VendorContentTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('contenttype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_contentype', to='ai_staff.contenttypes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_contentype', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VendorCATsoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('software', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_software', to='ai_staff.catsoftwares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_software', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VendorBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_email', models.EmailField(blank=True, max_length=191, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=191, null=True)),
                ('bank_address', models.TextField(blank=True, null=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=191, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=191, null=True)),
                ('iban', models.CharField(blank=True, max_length=191, null=True)),
                ('bank_swift_code', models.CharField(blank=True, max_length=191, null=True)),
                ('bank_ifsc', models.CharField(blank=True, max_length=191, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=191, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=191, null=True)),
                ('other_bank_details', models.CharField(blank=True, max_length=191, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TranslationSamples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('translation_file', models.FileField(blank=True, null=True, upload_to=ai_vendor.models.user_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('lang_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translationfile', to='ai_vendor.vendorlanguagepair')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MtpeSamples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sample_file', models.FileField(blank=True, null=True, upload_to=ai_vendor.models.user_directory_path_1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('lang_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mtpesamples', to='ai_vendor.vendorlanguagepair')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='vendorlanguagepair',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at', None)), fields=('user', 'source_lang', 'target_lang'), name='unique_if_not_deleted'),
        ),
    ]
