# Generated by Django 3.2.4 on 2022-01-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_vendor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorsinfo',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
