# Generated by Django 3.2.12 on 2023-03-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_vendor', '0001_vendor01'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorsinfo',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorsinfo',
            name='cv_file_display',
            field=models.BooleanField(default=True),
        ),
    ]
