# Generated by Django 3.2.4 on 2022-06-16 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_staff', '0006_currencybasedoncountry_mtlanguagelocalevoicesupport_mtlanguagesupport_projecttype_projecttypedetail'),
        ('ai_vendor', '0002_vendorsinfo_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorOnboardingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onboarded_as_vendor', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='vendorlanguagepair',
            name='unique_if_not_deleted',
        ),
        migrations.AddField(
            model_name='vendorlanguagepair',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lang_pair_currency', to='ai_staff.currencies'),
        ),
        migrations.AlterField(
            model_name='vendorsinfo',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_currency', to='ai_staff.currencies'),
        ),
        migrations.AlterField(
            model_name='vendorsinfo',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_legal_type', to='ai_staff.vendorlegalcategories'),
        ),
        migrations.AddConstraint(
            model_name='vendorlanguagepair',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at', None)), fields=('user', 'source_lang', 'target_lang', 'currency'), name='unique_if_not_deleted'),
        ),
        migrations.AddField(
            model_name='vendoronboardinginfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_onboard_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
