# Generated by Django 3.2.12 on 2023-06-20 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_vendor', '0002_auto_20230327_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_vendor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('customer', 'vendor')},
            },
        ),
    ]
