# Generated by Django 3.2.12 on 2023-06-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_vendor', '0003_savedvendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorlanguagepair',
            name='primary_pair',
            field=models.BooleanField(default=False),
        ),
    ]
