# Generated by Django 3.2.4 on 2022-06-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_vendor', '0003_auto_20220616_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorserviceinfo',
            name='mtpe_hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='vendorserviceinfo',
            name='mtpe_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='vendorservicetypes',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='vendorservicetypes',
            name='minute_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='vendorservicetypes',
            name='unit_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
